### ISSUE TITLE
NH Terminal doesn't enter into kali Shell

### ISSUE THREAD

**Issue by SyedTahseen** [offensive-security/kali-nethunter#1041]
## Issue: I installed Nethunter on my device but when I open the Nethunter terminal and choose kali it just Close the terminal if I start it and choose Supersu and by entering bootkali then login here i find option root@kali 
What is the matter how I can't directly enter into kali shell ?  And also gui of nethunter is showing just white screen how can I fix this ?

**Comment by Prodject** [comment]
I had a problem after installing NetHunter latest version when you open the terminal the error "App stopped", this error can be corrected by removing the terminal and put the terminal from version 3.15.4.
[Term-nh-3.15.4.zip](https://github.com/offensive-security/kali-nethunter/files/1476294/Term-nh-3.15.4.zip)

**Comment by otanim** [comment]
@Prodject not working tho..

**Comment by Sk8793** [comment]
go to the folder /data/local/nhsystem n delete kali-armhf
then go  nethunter app there should be an option install chroot do install then select minimal then download your files

**Comment by HyperThred** [comment]
I know this comment is closed, but I'm new to Kali NH and u also can't seem to get terminal to work. I should say it opens I think into the Kali command but no where do I see root@kali: /#

All I see is 
: /#    without root@kali

But when I open terminal and am promoted to click on Kali or Androidsu, I chose Kali and it opens. I just don't see root@kali

**Comment by kimocoder** [comment]
Try go into NH term and normal shell, not Kali Shell. Type "su" and "bootkali" result?

**Comment by yesimxev** [comment]
Do you have the latest Nethunter Terminal + Nethunter app? Sometimes also been resolved if I reinstalled them, of course if the above commands work, which @kimocoder said

**Comment by HyperThred** [comment]
I have a Google pixel 2 XL. I use the Kali nethunter download for the OnePlus one CM 12.1 zip file. Everything else seems to be working well. As far as the versions of the nethunter terminal app the version I have is 1.0.0 and the nethunter app version is 3.0

**Comment by HyperThred** [comment]
I tried the command SU and bootKali. I didn't put parentheses around that, I didn't think I was supposed to. I did also try what Prodject said with the different version of termNH but no luck there either. I'm sorry if these are dumb questions. Like I said I am brand new to this stuff and I just want to learn a little bit more about Kali nethunter and Kali Linux. I thought I would start by putting it on my phone. I should say that I have an Nvidia shield k1 tablet and all is working perfectly well on there. My terminal app fires up with no problems. I am just trying to get it on my phone which is running Android 9.0. I've heard some say that the version of Android is the problem but I just am still trying to figure this out.

**Comment by HyperThred** [comment]
I know this thread is closed. Should I open a new one regarding this issue?

**Comment by yesimxev** [comment]
Oneplus One? You should have downloaded a generic nethunter kalifs installer + kernel installer to make your device working. I was assuming you have those. Oneplus kalifs installer has oneplus one kernel, it's a miracle that your phone boots with that to be honest. If you reinstall your OS, and apply initial android setup, install a generic kalifs. That will leave the original kernel on your device, if you do not require wireless injection + HID, CDROM (DriveDroid) compatibility. 

My links for (kind of latest) generic kalfis:
`https://github.com/yesimxev/nethunterkalifs`

Otherwise, if you need them:

You might have to build your own kernel, as it does not exist for your device. (you can look up patched kernels here: https://github.com/offensive-security/nethunter-devices/blob/master/kernels.txt )
Also you can try to use the same HID, CDROM patches from this Pixel C patched kernel:
`https://github.com/jcadduono/android_kernel_google_chromeos/commit/d1b9e77f408ebc90f561647257d16c9ceacd9e3a`
`https://github.com/jcadduono/android_kernel_google_chromeos/commit/1bd806b1a67ca38f0b8ea81605ddef13baf05a35`
To apply to the oirignal kernel source below:
Kernel source:
`git clone https://github.com/kerneltoast/android_kernel_google_wahoo.git -b 9.0.0-sultan`
By following the tutorials:
`https://github.com/offensive-security/kali-nethunter/wiki/Porting-Nethunter`
`https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel`
Then putting the kernel (z)Image(.dtb) + modules into the nethunter-installer, and making an installer zip for your device.
`git clone https://github.com/offensive-security/kali-nethunter.git`

**Comment by yesimxev** [comment]
I can see your case is resolved in another issue, but I wil leave the above instructions, might help others. Still useful if you have any problems after using Oneplus One installer though

**Comment by jcadduono** [comment]
the command to enter the Kali environment from an android terminal is actually `su 0 bootkali_login`
I highly recommend using JuiceSSH's local terminal. It's one of the best functioning terminals available on Android with full ncurses support.

@HyperThred I would not open a thread since that is an extremely old version of Kali NetHunter and most of its issues are already fixed. If you have an unsupported device and wish to use just the rootfs, app, etc. and not have full kernel support then I recommend a generic arm64 zip.
Here, try https://build.nethunter.com/nightly/2019.03-13-0514/nethunter-generic-arm64-kalifs-full-rolling-2019.03-13-0514.zip
