### ISSUE TITLE
TP-Link WN722N isn't detected by NetHunter

### ISSUE THREAD

**Issue by Andrewerr** [offensive-security/kali-nethunter#1129]
### Device:
Samsung Nexus 9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

5.1.1 Lollipop

### Built from repo (date and build command) or downloaded from website (links):
Downloaded from https://images.offensive-security.com/nethunter-release/nethunter-flounder-lollipop-3.0.zip

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

`Linux version 3.4.67-00092-g7b02438 (root@kali) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Thu Sep 24 01:04:17 UTC 2015`

## Issue:
My tp-link wn722n isn't detected by NetHunter.
After connecting it I am seeing following in dmesg:
  ```
[  790.687045] usb 1-1: new high-speed USB device number 3 using s5p-ehci
[  790.822495] usb 1-1: New USB device found, idVendor=2357, idProduct=010c
[  790.823196] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  790.823828] usb 1-1: Product: 802.11n NIC
[  790.824187] usb 1-1: Manufacturer: Realtek
[  790.824538] usb 1-1: SerialNumber: 123456789
```
lsusb:
```
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Function not implemented
Bus 001 Device 004: ID 2357:010c  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```
Firmwares:
```
ar3k           ar7010.fw  ath3k-1.fw   htc_9271.fw  rtl_nic
ar5523.bin     ar9170.fw  ath6k        RTL8192E     rtlwifi
ar7010_1_1.fw  ar9271.fw  htc_7010.fw  RTL8192SU
```
ifconfig wlan1 up says that there is no such device
iwconfig also doesn't see wlan1 or any other wireless devices except wlan0

**Comment by vishalshelar882** [comment]
Which model of tp-link

**Comment by 0E800** [comment]
You have the wrong version. You need a v.1 with atheros chipset. I don't
think the realtek chipset supports injection and/or monitor mode.

**Comment by Andrewerr** [comment]
But why it is not detected in iwconfig?

**Comment by 0E800** [comment]
Probably because the kernel doesn't include the firmware source. Possibly
because theres no point in adding support for a device that has no relation
to capturing and injecting packets.

I'll order one of the current versions and see what it takes to make it
work. If it can't manipulate the aether then it's useless as a auditing
tool.

I'm the mean time, Google the exact chipset and read about how to install
the firmware on an older Linux kernel .

The great thing about the world wide web is that for every question you
think is unique , most likely someone has already had it and found the
answer. It's up to you to be consistent in searching for it by any means
necessary.
