### ISSUE TITLE
Nethunter apps (APK files) are not installed on LineageOS 15.1

### ISSUE THREAD

**Issue by ajes** [offensive-security/kali-nethunter#1195]
### Device:
OnePlus One

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
LineageOS 15.1

### Built from repo (date and build command) or downloaded from website (links):
official website

## Issue:

After installing Nethunter-rootfs in twrp recovery, APK apps are not installed in system. There is no error during installation in twrp, but apps just aren't installed. Manual install in LineageOS (by clicking on APK files) successfully installs them.

**Comment by noyb666** [comment]
So are you saying your stock image is LineageOS 15.1? And how did you install Nethunter? Did you use the Kali NetHunter Linux Root Toolkit (LRT) ?

**Comment by ajes** [comment]
I have used official nighlty nethunter-rootfs file and installed it the same way as on normally supported rom (in twrp).
And yes, I am using LineageOS 15.1.
I have also tried with custom build rootfs, but it did not help.

**Comment by amzker** [comment]
Install manually

**Comment by noyb666** [comment]
So to answer my question: you did not use the LRT. 
And when you say: "installed it the same way as on normally supported rom (in twrp)." does that mean you adb pushed it to TWRP and than flashed it just like you did with Lineage?

**Comment by noyb666** [comment]
And when you say: "I have used official nighlty nethunter-rootfs file" Do you mean you downloaded a nightly from here: https://build.nethunter.com/nightly/2017.11-18-1618/   ? And if so, which one did you exactly take, because there are only nightlies for the different Google flavours, but none for Lineage...?

Sorry, a lot of questions, but the install guides are very inconsistent and confusing...

**Comment by amzker** [comment]
I Am Also Lineage User
And use Nethunter GUI Also
Not Need To Flash
Just
Extract Zip Of Nethunter
Copy Busy box in /system/xbin
And in /root
Than Install App
Than Put Kalifs.zip On internal storege
Open nethunter app
And i stall chroot
All done!

**Comment by ajes** [comment]
I have used generic one nethunter-generic-armhf-kalifs-full-rolling-2017.11-18-1618.zip. Only kernels are specific for devices.

**Comment by noyb666** [comment]
"Only kernels are specific for devices." Sure, makes sense. 
So I flashed now : nethunter-generic-arm64-kalifs-full-rolling-2017.11-18-1618.zip and kernel-nethunter-angler-oreo-2017.11-18-1618.zip on my device and it starts up with the Nethunter welcome screen which is big progress, because following the LRT instructions absolutely nothing happened.
But unfortunately it gets stuck after that in a endless loop falling back to the Google welcome screen... and won't start up...

**Comment by noyb666** [comment]
@ajes So I followed your description and finally it looks good. Have Lineage OS and Nethunter installed seemingly correctly. But except the awesome Kali welcome screen no trace of Nethunter on the device...
That's exactly what you described, isn't it? But could you elaborate what you mean by: "clicking on APK files successfully installs them." ?? Sorry, I'm such a newbie and need a description... Where are the APK files?

**Comment by ajes** [comment]
@noyb666 APK are placed under: /data/app . I have opened it in file manager and then installed APK from there.

**Comment by noyb666** [comment]
Ok, thanks a lot for your reply. I searched in the settings and under apps from unknown sources and couldn't find anything... But on my trial and error quest I found the  apk apps online to download and thought you meant that...: 

https://forum.xda-developers.com/android/general/kali-nethunter-android-device-t3596625

and it worked!  Although the Kali chroot wouldn't install on the first try, but I reinstalled over it (the apps again) and it worked on the second try. But maybe it's a bit messy now, so I will give it a second try and follow your way, since it's more logical, no need to download anything since they are already on the device....

**Comment by noyb666** [comment]
One more question about rooting the device since you are also a Lineage user:
Following the otherwise excellent Lineage Install Guide I flashed the  "LineageOS su add-on" just the way it is explained in the guide.

Result: TWRP confirmed the flash, but nothing (visible) happened on the device and checking:

adb shell
angler:/ $ su
Permission denied

shows that the device is not rooted.

How did you root? And when? I mean: before flashing Kalifs or after ? And while SuperSu would brick the device reliably I managed to flash eventually Magisk and that worked immediately, but I'm curious to hear about your experience.

**Comment by ajes** [comment]
@noyb666 I don't think so it is a good place to ask such a question, as it trash the issue we have here.

To answer, you need to enable it via Developer options.

**Comment by noyb666** [comment]
Oh, you're saying I'm going off topic and hitchhiking the thread...?
Ok, I'm sorry about that and will stop. 
Sure I open a new thread then, much better.
And thanks for your help.

Back to topic: I installed again freshly and activated the apps manually just as you described, worked, thanks for your input.

**Comment by yesimxev** [comment]
I can confirm the LRT question on OnePlus1. Installing with all fresh nethunter-LRT, freshly built kalifs with nethunter-fs and the only kernel I found, still leaves the apks (shows installed in LRT/TWRP). Could be some security thing as it says when installing manually, that the app can be harmless.. 
Got AddonSU, SuperSU, SELinux permissive, Google protect off. Intial setup done of course

**Comment by 0E800** [comment]
Try Nougat or better yet Lollipop or any official build for the device. Use 
a device other than your personal phone. Nobody has stocked the fridge with 
beer here in over a year. Get over it upgrade junkies.

If you really want it to work , stop picking at pipe dreams of your 
personal phone running Nethunter. This platform was never meant to run on Oreo.
@0E800
╔█████╗ ╔███████╗
██╔═████║██╔════╝
██║██╔██║█████╗
████╔╝██║██╔══╝
╔██████═╝███████╗
╚════≪8⊘⊘≫═════╝
   🅼🅸🅽🅳 ᵃˢ ⲱⲉⲁⲣⲟⲛ

**Comment by TheMMcOfficial** [comment]
You need to flash the "LineageOS su add-on" and allow certain apps to access at the root privilege. 
Normaly you can find something about that in the settings or you can install an app like magisk or superSU to managed it.

**Comment by yesimxev** [comment]
After SuAddon, enabling root for apks and adb, disabled google protect, and find my phone (probably not neede, but did everything I found) the problem still exists. I guess nethunter-installer does the install command with SuperSU, didn't have a look into that though

**Comment by TheMMcOfficial** [comment]
You can install magisk and install the Nethunter profile. You will get all the apps you need if some aren't install you can find the apks here: https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer/update/data/app

**Comment by yesimxev** [comment]
I saw instructions and I might give a try once I can compile Lineage 15.1 kernel and if it's necessary

**Comment by 0E800** [comment]
I have not seen confirmation that wireless injection is supported with Magisk

**Comment by TheMMcOfficial** [comment]
https://github.com/atarii/Magisk_Kali_Nethunter

"Not Working:
Anything which requires the custom kernel/ramdisk will not work out of the box. This includes:

Wi-Fi injection (requires custom kernel/ramdisk)
HID Interfaces (BadUSB/Duckhunter etc. - also requires custom kernel/ramdisk)"

So if you build the kernel everything should work.
