### ISSUE TITLE
[Question]Nexmon

### ISSUE THREAD

**Issue by mirzaatifbaig** [offensive-security/kali-nethunter#1203]
## OS version:Marshmallow

Question:So,as all the forums and groups about this project are dead I decided to ask it here.Recently I saw a project named Nexmon offering monitor mode support on bcm 4339.I wanted to give it a try and bought a cheap Note 3(Shortage of Nexus 5).I was able to run monitor mode with LD_PRELOAD,It had injection support and captured wpa handshakes and tested it against my own AP.Now I ran a chroot using linux deploy and strangely it didn't recognize the monitor mode.My Question are
1-How can I support Monitor mode inside the chroot.
2-The nethunter kernels are patched for external injection support will installing it and setting libraries work for internal one?
As the nexmon project is new to nethunter there aren't many guides on making it work inside the chroot environment.

**Comment by TheMMcOfficial** [comment]
1- I don't know if it's possible. You can search in the repo for issue who contain: "Nexmon" and read them. I'm not sure but I haven't hear someone who make it work. 

2- You can replace the firmware to use the nexmon patch when you recompile a kernel. For the libs like libnexmon.so or the nexutils tools I don't think you will be able to place them in the kernel. You can follow those step to compile a kernel with some nethunter tools. 
https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel

**Comment by mirzaatifbaig** [comment]
It is possible.I've done it.But starting airmon-ng or any monitor mode script inside causes a kernel panic

**Comment by 0E800** [comment]
There is a kernel module for bcm4339 . you didn't include what you had to do to get it working originally. Did you use stock ROM ? Did you have to root it?

If your android environment using the integrated WiFi adapter how would the chroot environment have any chance of using it? 

For wireless auditing you want to reach further than the puny built in antenna can do and a lot of times the kernel breaks when you try to enable all atheros and broadcom.

Either the nethunter kernel you flashed didn't include the kernel mods or your android environment is playing tug of war with kalifs chroot.  You can't use the same interface for both environments.

**Comment by 0E800** [comment]
Way to put me in my place ;hj thank you for lacing my boots with some higher education. (no sarcasm)

I didn't realise you could achieve packet injection / handshake harvesting through native android like that. I'm still in the early kernel dev mode of "when in doubt comment it out " gimme more bacon.

For the nexus 7 flo kernel I am working on trying to add nougat and or Oreo NH support; I have a similar issue with the device hard rebooting after monitor mode is enabled but not until I physically pull the tplink WiFi or quit wifite.

Even though not identical as you are using internal WiFi and in external adapter .. I still think it could be  related. 
There is a command that is used that has the same effect of of airmon-ng stop but it did not cause the device to reboot. What I did was replace airmon stop with the alt command in the scripts I was using .

I'll try to find the command. I think your issue is related to power but I'll find what jcundo (misspelled ) said.

**Comment by 0E800** [comment]
I found my old post...

Review:
https://ubuntuforums.org/showthread.php?t=1979338
Use techniques provided to dig, DIG DEEP.

Follow the trail and report what you find,

As an alternative you can try: nmcli device wifi rescan or nmcli device wifi list

Does that reboot it?

**Comment by mirzaatifbaig** [comment]
Found it.Turns out the 5ghz channels are what causing the reboots.They demand too much goddamn power to function which causes the kernel to panic.I think there is a patch in the nexmon forums.And yeah the external adapter rebooting can also be solved via it.It's just the chroot demanding more power(F***loads Seriously)Of power.I mean the power demand is too goddamn high.

**Comment by mirzaatifbaig** [comment]
https://mirrors.deepspace6.net/Linux+IPv6-HOWTO/x1028.html none of them Cause anything at all Just the monitor mode commands of airodump-ng etc.
