### ISSUE TITLE
Not working hid attacks winth NetHunter

### ISSUE THREAD

**Issue by NicuLamer** [offensive-security/kali-nethunter#1266]
### Device:
Xiaomi redmi note 4x

### OS version 
Nethunter OS (Lineage OS) Nougat

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Guu

## Issue:
When i am trying to make a hid attack or duckhunter hid
Nethunter writing that:
Attack launched...
Attack execution ended.

Kernel version:
Linux version 3.18.31-perf-g818479a (builder@mi-server) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Thu Mar 16 09:18:28 WIB 2017

Hid interfaces:
/dev/hidg0
This is also written when I am not connected by usb cable

BusyBox version:
v1.25.0-NetHunter

![screenshot_20190303-100839](https://user-images.githubusercontent.com/45120674/53692643-56aece80-3d9c-11e9-8adc-371576f563e2.png)

Somebody please help me with this trouble

**Comment by jcadduono** [comment]
This device is not supported by NetHunter, and the hidg interface you are seeing does not contain the same functionality as the 'hacky device' provided by the HID device emulation driver we include in our custom kernels for supported devices.
You will need to use a NetHunter kernel in order to support the use of NetHunter related USB functions like HID emulation and external wireless adapters in monitor mode.
