### ISSUE TITLE
WPS attack not working

### ISSUE THREAD

**Issue by melvinsh** [offensive-security/kali-nethunter#15]
WPS attack just hangs at "0/0 success/ttl" using Wifite on every AP.

Hardware:
Nexus 5
TL-WN722N

**Comment by peterpt** [comment]
i am using Nexus 7 (2012)
I like to do everything manually , by saying this i mean using reaver and aircrack tools , i like it that way because i get a lot of APS that need aireplay authentication on specific time frame , and wifite is not able to do that properly .

manually , airodump work like a charm 
http://s15.postimg.org/6qswmuygb/airodump.png

reaver too
http://s14.postimg.org/al8mzdomp/reaver.png

i use rtl8187 to do the job
http://s17.postimg.org/vbb1j9mrj/lsusb.png

one thing strange that i found when i try wifite , is what you are saying , witch is that we are unable to see if wifite is working properly or not because it stays at 0/0 of successful attacks , but if you notice on my next image you will see that the percentage of the attack is increasing , this could mean that wifite is working perfectly but the script may have some issues on the android versions 

http://s10.postimg.org/6ti8wf5uh/wifite.png

**Comment by peterpt** [comment]
one thing more that i missed .
"iw reg set BO" =( increasing transmission power of the wifi adapter ) don't work on nethunter , at least for me .

**Comment by cr1p70** [comment]
[quote]peterpt commented on Jan 23
one thing strange that i found when i try wifite , is what you are saying , witch is that we are unable to see if wifite is working properly or not because it stays at 0/0 of successful attacks , but if you notice on my next image you will see that the percentage of the attack is increasing , this could mean that wifite is working perfectly but the script may have some issues on the android versions [/quote]

yup this is happening to me when running Wfite on all my devices running nethunter an a tplink, havent tested with alpha card, and i haven't tried anything else just trying to get get wifite to work.
 i've never used it till now im used to manual methods an im thinking is what ima end up having to do cause im getting no where with wifite.

**Comment by Goran7777** [comment]
I try ten days for alive kali 2017 and noone app doesnt work anymore,bully,wifite,reaver is also full of bugs,maybe some new app exist but i dont know which app.
