### ISSUE TITLE
sshd logging appears to be non-functional

### ISSUE THREAD

**Issue by nullsign** [offensive-security/kali-nethunter#187]
SSHD's logging seems to not be working. While the facility is set to AUTH, and the level to INFO - auth.log never populates with any data.

**Comment by binkybear** [comment]
I was only able to partially produce error.  In my case I was able to write to auth.log after first creating a file in /var/log and then starting the rsyslog service.  Discussed with nullsign and nullsign was still unable to get auth.log to populate with data.

Unsure if this is due to a setting a sshd_config or maybe another issue.  Will leave open for time being.
