### ISSUE TITLE
How to use USB Ethernet adapter

### ISSUE THREAD

**Issue by DrDinosaur** [offensive-security/kali-nethunter#193]
I have a USB to Ethernet adapter. I plugged in the cable, but I'm not getting anything on ifconfig. The device shows up off and on on lsusb. Is there something I need to do to get the interface activated and working?

**Comment by m27frogy** [comment]
Have you tried ifconfig -a or ifconfig eth0 up?

**Comment by kapel1044** [comment]
im pretty sure he tried thats why hes asking, anyways i tried just now and the interface is showing up only with lsusb

**Comment by binkybear** [comment]
@kapel1044 - Have you tried turning off the wifi to see if it makes a difference? (assuming you didn't)

**Comment by kapel1044** [comment]
To be honest it was yesterday but i'm sure i tried with wifi dongle off and internal off since i was trying to setup that adapter first for later use with MANA. Later of course wifis were on and still no-go.
Even with orWall disabled and still nope. (firewall+iptables route for Tor apk that blocks all traffic apks which aren't marked to use Tor) 
I will double check tonight or tomorrow, have to re-flash Kali 4.4.4, coz it doesnt work either with PwnieExpress 2014 flashed. 
Is it possibly adapters fault ? lsusb says Bus 001 Device 004: ID 0fe6:9700 Kontron (industrial Computer Source / ICS Advent) DM9601 Fast Ethernet Adapter
Coz it didn't work on windows 7 pc out of the box, it had to download some drivers automatically with cable plugged to motherboard, not through dongle.

**Comment by binkybear** [comment]
@kapel1044 - The problem appears to be that the particular device is not enabled in the kernel.  See:

https://github.com/binkybear/flo/blob/ElementalX-4.00/arch/arm/configs/kali_defconfig#L1682

I can enable it in the next build.  Most usb  >ethernet use AX8817X so it's hard to judge what everyone is using.

**Comment by kapel1044** [comment]
cool, thank you so much. i thought i would have to wait till 5.x :) meanwhile i could build my own maybe

**Comment by kapel1044** [comment]
by the way, is kali 2.0 coming ARM on the same date ?

**Comment by binkybear** [comment]
Yes, it should be.  Were looking to do a Nethunter update same date as Kali 2.0.

**Comment by kapel1044** [comment]
keep up amazing work :)
