### ISSUE TITLE
Nexus 4 : missing usr/bin folder 

### ISSUE THREAD

**Issue by bfaure31** [offensive-security/kali-nethunter#223]
Hi,

I have just install nethunter zip file from TWRP recovery interface on my Nexus 4, paranoid and android 4.4.4.

I wanted tu update Kali but find that /usr/bin folder with scripts is missing.

**Comment by binkybear** [comment]
Scripts should be installed to /system/bin or /system/xbin outside of kali (in android).

**Comment by bfaure31** [comment]
Yes, binkybear, I think I saw few of them in /system/xbin. How should I list all of them and transfer them into kali environment ?

**Comment by bfaure31** [comment]
An update, after some research : all nethunter binaries, such as apt-get or 7z for example, are missing. I tried to reinstall nethunter several times, but usr/bin folder is never created. I didn't find where the install program put those missing binaries.

**Comment by binkybear** [comment]
The scripts in /system/xbin do not need to be transferred into chroot.  I would suggest a manual reinstallation if you are missing a /usr/bin folder in chroot.

**Comment by Orwell1984** [comment]
I had the exact same problemen with the Nexus 5 on both KitKat and Lollipop. After reading somewhere that this issue could be caused by a lack of free storage space, even though I still had at least 1 GB unused after the install, I freed an extra 2 GB. Everything installed fine and complete after that.
