### ISSUE TITLE
Updating metapackages crash

### ISSUE THREAD

**Issue by nicking989** [offensive-security/kali-nethunter#292]
After a fresh install with the new nethunter and terminal apps, the nethunter terminal crashes when you try to install the nethunter metapackage using the nethunter app.
I'm on a Nexus 4 running Android 5.1.

**Comment by binkybear** [comment]
Is this the latest custom nethunter terminal (built in the last few hours)?

**Comment by nicking989** [comment]
Yes it is

**Comment by jmingov** [comment]
True, i missed a if in the code. thanks for the feedback @nicking989

Im doing some checks, the problem is: we are launching the terminal without all the needed params.

But the bug is in the nethunter apk (launching a incomplete intent). The terminal does a ForceClose because of this.

Im pushing a fix soon.

Jaime

**Comment by nicking989** [comment]
Thanks, and no worries.
