### ISSUE TITLE
(Nexus 6 Marshmallow) Mana Tookits issue

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#316]
@jmingov @binkybear @TheNain38 
Thanks for the hard work you guys have done. While testing the HID issue, I am having anther issue found in Mana Tookits. But maybe just need a little fix here,

It happens to `start-nat-full-lollipop.sh`, `start-nat-simple-bdf-lollipop.sh`, `start-nat-simple-lollipop.sh`.
When the first time I run each of them, it can start up my wifi dongle and set up properly until it comes to echo the string `Hit Enter to kill me`, it will be followed by an error `"iptables-restore: line 21 failed"` and then will stop running the script, force to quit.

After googling, in the script, I tried to change the name `/tmp/rules.txt` to `/tmp/iptables.rules`, now they can run the script again until I press ENTER to stop it, but still it reports the same error as mentioned above, meaning only iptables-restore fails. But when I changed `/tmp/iptables.rules` back to `/tmp/rules.txt` again, it still can run the script without force quit. So, I have no idea.

One more thing, I think there should be `-i ` missing in between `dns2proxy.py` and `$phy&` inside `start-nat-full-lollipop.sh`.

Seems everything is work fine with Mana tookkits other than the issue mentioned above.

Thank you very much.

**Comment by jmingov** [comment]
@simonpunk about the iptables error, since android 5 thers no iptables (we removed them from app menu also), so the errors are when iptablesrestore is trying to commit the restore. (And doesnt work)

So i removed the save/restore from all lollipop scripts (same for marshmallow), no needed.

Also as you pointed, the interface swich (-i) in dns2proxy was missing, added it too.

Once @offensive-security updates the nethunter-utils package all should be fixed.

You can apt-get update && apt-get upgrade (ill update here when the package is updated, dont try right now ^^)

Ty!


https://github.com/offensive-security/nethunter-utils/pull/11
https://github.com/offensive-security/nethunter-utils/pull/10
https://github.com/offensive-security/nethunter-utils/pull/9
https://github.com/offensive-security/nethunter-utils/pull/8

**Comment by simonpunk** [comment]
@jmingov Thank you very much, it can be closed now.

**Comment by jmingov** [comment]
Yep, @offensive-security  updated package few hours ago in sana repos.

Jaime
