### ISSUE TITLE
Nexus 6 Stuck in Boot Loop Following Nethunter 3.0 install

### ISSUE THREAD

**Issue by 3mrgnc3** [offensive-security/kali-nethunter#330]
I already had Nethunter 1.0 installed, then upgraded to 2.0 previously,

I re-used the Nethunter Installer .exe for windows that I used the last two times I installed Nethunter.

This time I got the following error in TWRP following install and now I'm stuck in a boot loop.

![2016-01-08-005947](https://cloud.githubusercontent.com/assets/6823590/12187467/19f9581c-b5a4-11e5-9e0a-3f8c11c1134c.jpg)

![2016-01-08-010104](https://cloud.githubusercontent.com/assets/6823590/12187483/38ee32e2-b5a4-11e5-9a7e-f018e2cd54d4.jpg)

Please advise on a solution and provide a fix.

Kindest Regards.

**Comment by binkybear** [comment]
"I re-used the Nethunter Installer .exe for windows"  <-- That no longer works and should not be used to install Nethunter as it is outdated.  I would suggest following instructions on Wiki or using https://github.com/offensive-security/nethunter-LRT.  In order to fix you will need to restore factory image.

**Comment by 3mrgnc3** [comment]
Thanks for the update so quickly, i really appreciate it.

I'm doing as you said.

Cheers.
