### ISSUE TITLE
Nexus 9 Lollipop Flushing issue

### ISSUE THREAD

**Issue by adawoing** [offensive-security/kali-nethunter#335]
on the flashing stage of nethunter --> during updating partition details stage , the error showed multiple times 
"E:error opening 'data/local/nhsystem/kali-armhf/dev/ram12'
E:error : Not a directory........"
too many errors on ( loop#,ram#)
then it says done , i rebooted the device but it got me back to the recovery mode.
i used "nethunter-flounder-lollipop-3.0.zip" , and its not corrupted file for sure.
any idea how to fix this issue?

**Comment by yavuzgokhan** [comment]
I had same problem too on my nexus 9 6.0.1 stock rom. But i doon't have any problem about working my os and nethunter. I think it is not important error.

**Comment by adawoing** [comment]
i am unable to go to nethunter , i thought it could be because of this error. After flashing the device with nethunter ,it always take me to TWRP after reboot. How can i use nethunter in such state?

**Comment by jmingov** [comment]
Clean Stock flash recommended.

**Comment by brsgdc** [comment]
I have same issue on OnePlus One. Please update your images.

**Comment by binkybear** [comment]
The error: "E:error opening 'data/local/nhsystem/kali-armhf/dev/ram12'

Is the installer trying to follow a symlink that doesn't exist.  This is not an issue with Nethunter.  As far as images not working with OnePlus, it works fine on 12.1 on a clean flash.

**Comment by brsgdc** [comment]
I tried to install nethunter over stable cyanogenmod but still not working.

**Comment by binkybear** [comment]
We recommend doing a clean wipe and using the factory CyanogenOS.  Did you use that or daily builds from CM?  I can only speak from my experience and daily testing.

**Comment by brsgdc** [comment]
I don't really understand. Why you don't release new update. The problem seems like old version of nethunter. Between 2.0 and 2.0.1 for oneplus one.

**Comment by jmingov** [comment]
@brsgdc, beacuse we flash the images without problems, we dont fix problems that we dont see or we can not reproduce.

Also, fyi this is a open source proyect, submit the a fix if you think ther is an error.

Opo is the most used device, we dont rebuild nothing because 1-2 persons are unable to flash it properly.

**Comment by adawoing** [comment]
i am not saying this image has problem , if it worked with all of you then it's obvious from the way i flashed nethunter image . i followed this guide "https://github.com/offensive-security/kali-nethunter/wiki/Windows-install " but the last step wan't clear "Installing the NetHunter Image" .This is what i have done.
-i rebooted on the recovery mode ,it took me to TWRP.
-i choose install ,then i picked "nethunter-flounder-lollipop-3.0.zip"only which i already copied in /sdcard/DCIM
-i flashed it ,it started with every installation went fine except for "updating partition details" . Chroot took longer time ,but it finished .
-it finished then i rebooted the device ,it showed google then took me to TWRP "it took longer to load" .
-this error showed in three places during the installation (before decryption part ,after decryption part, after the installation.
Can anyone tell what i done wrong during the flash ? there should be something i am missing/doing it wrong since it worked with everyone.

**Comment by jmingov** [comment]
You skkiped the most important step:

unlocking your device and updating it to stock AOSP or CM in the case of OPO. (Check point 1.0 for supported roms)

https://github.com/offensive-security/kali-nethunter/wiki#40-installing-nethunter-on-your-android

**Comment by brsgdc** [comment]
Which version of cm 12.1 do you offer for opo ?

**Comment by adawoing** [comment]
i did unlock the device & updated it to stock AOSP "Nexus 9 (volantis) 6.0.1" , it was step 3 & 5 on this guide "https://github.com/offensive-security/kali-nethunter/wiki/Windows-install" . what else am i missing?

**Comment by brsgdc** [comment]
I get same error messages but it's working for me now.

**Comment by gerrydoro** [comment]
Hey guys, I followed ALL the steps at [this guide](https://github.com/offensive-security/kali-nethunter/wiki/Windows-install) but I have those errors like @brsgdc :

> "E:error opening 'data/local/nhsystem/kali-armhf/dev/ram12'
E:error : Not a directory........"
too many errors on ( loop#,ram#)

I tried to ignore the errors and reboot the system but during the boot animation (not the kali boot animation but the stock Cyanogen OS 12.1.1) my OPO freeze so I'm obligated to wipe all and restore my backup. 
@jmingov I don't blame you, but this error is common to a lot of people (just try to google "E:error opening 'data/local/nhsystem/kali-armhf/dev/") so I think there is a problem in the last image of Kali NetHunter

P.S. In another try, my opo boot up but the stock Cyanogen OS 12.1.1, without any kali tool :(

> Sorry for my bad english

**Comment by Nekrose483** [comment]
i get these same errors. i completely understand its non-existant symlinks from TWRP, but i'm not sure where else to post. everything else works fine. everything is installed, kali terminal, router keygen, etc, even the boot screen is there. the only thing i can't seem to find is the kali nethunter app with the menu. kalimenu "nethunter home".. whatever its called.. it's just not there. on my third time flashing the nethunter zip now.. (on an OPO CM 12.1 with NH 3.0) worked perfectly before (i think it was an older version of NH though.. i'm using the newer zip now). i did a factory reset.. which caused me to loose the app. which is why i'm reflashing it. i've not flashed anything else on it.. bu t all of my data is on the phone. TWRP is installed and up to date as well. on other forums, people are saying the same thing where sometimes they just can't find the app... then after a few times of flashing it, it just.... works.

**Comment by harayz** [comment]
i started to see some weird behavior after uninstalling multirom...

**Comment by SierraJuliet** [comment]
Follow the instructions from here:  https://github.com/offensive-security/kali-nethunter/wiki

I am choosing to do via Windows (but also have it on Linux)

READ ALL THE FOLLOWING BEFORE DUPLICATING:  
(System will require Reboots and Tablet as well)
>Download "Nexus Root Toolkit v2.1.4" (see link in instructions above)
>Follow ALL instructions on "Toolkit"  by clicking the "Initial Setup"
>Run "Flash Stock + Unroot"
>Run "OEM Lock"
>Run "Unlock"
>Run "Root" (without "Custom Recovery" selected)
>Go to Google Play Store and download "TWRP" and "Busy Box" and "SuperSu"
>Run "Busy Box" (let it compile and then select "Install") <=SpuerSu should ask to allow program = Yes
>Drop NetHunter image on root directory of tablet (where all folders are when you open on Windows)
>Open "TWRP" and setup the "Recovery" for your particular device and then "Install Recovery"
>Reboot in TWRP and install NetHunter image
>Select all NetHunter options except "SuperSu v2.6"
>Select only the defaulted option (already checked)
>Once NetHunter is installed (**see "last comment" below**) open it on the tablet "Kali" icon
>Select "Kali Chroot Manager"
>Select "Add Metapackages"
>Select "Kali-linux-nethunter" and click "Install & Update"
>When that is done type "apt-get update && apt-get dist-upgrade"

...if you DID everything I said the image will update without any errors, such as "postgresql-9.4" fails

...if you DO get "postgresql-9.4 failed" messages then redo everything (including flash android image) because the NetHunter image will never update.  I had to do things at least 6 times as I tried different combinations.  This combination I just listed finally worked for "Nexus 7 2013 Wifi Only Android 6.0.1"


LAST COMMENT:  You may see this (see below) during NetHunter Install.  I have not figured out how to stop this from happening.  This should not affect anything I have already mentioned.

E:error opening /data/local/nhsystem/kali-armhf/dev/ram12
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram14
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram16
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram10
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram13
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram15
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/loop6
E:error: Not a directory
E:error opening /data/local/nhsystem/kali-armhf/dev/ram4
