### ISSUE TITLE
updating linux headers in NetHunter

### ISSUE THREAD

**Issue by gordoncoale** [offensive-security/kali-nethunter#348]
Using NetHunter on my Nexus 5.  Upon trying to run some python installs - for instance 

pip install netifaces
fails with errors from 
/user/include/netinet/in.h
Other pip's fail with similar header issues.

This seems to fail because of a known Kali feature/bug documented below and other places
https://www.reddit.com/r/Kalilinux/comments/3gob0p/kali_20_cannot_get_headers/

However running the suggested steps gives the failure 

>apt-get install -y linux-headers-$(uname -r)
fails with
E: Unable to locate package linux-headers-3.4.0-g12d78b6-dirty
E: Couldn't find any package by regex 'linux-headers-3.4.0-g12d78b6-dirty

Any suggestions?

**Comment by offensive-security** [comment]
1) The Kali chroot does not share a kernel with NetHunter, the Nethunter kernel and Kali kernel are two separate and distinct entities. 
2) The "feature/bug" you link to was due to the OP not running "apt-get update" after making their changes. 
3) Try using the full name of the linux-headers package you want to install instead of using $(uname -r).

**Comment by anietie** [comment]
I wish all this didn't have to be this complicated.
