### ISSUE TITLE
(Nexus 6 Marshmallow) [echo -ne "\x00\x00\x00\x0a\x00\x00\x00\x00" > /dev/hidg0] doesn't output the letter "g"

### ISSUE THREAD

**Issue by simonpunk** [offensive-security/kali-nethunter#355]
I forgot to say that the upper letter "G" doesn't come out as well when using 
`echo -ne "\x20\x00\x00\x0a\x00\x00\x00\x00" > /dev/hidg0`
No idea what's going on here..

**Comment by jmingov** [comment]
Hello @simonpunk 
COMMENT WROTED USING DUCKHUNTER
Going to print 5 g's and 5G's
ggggg GGGGG
Looks like is working here.

**Comment by binkybear** [comment]
@jmingov: I believe he is correct with the "G" error.  In duckhunter we are using us_bin so that passes it to hid-keyboard instead. If @simonpunk  were to do it manually I believe passing the above string I believe he would encounter the problem.  

It's an issue but not a big one since we use us_bin now and we can just pass the letter "G" to hid-keyboard.

**Comment by simonpunk** [comment]
@jmingov
still don't know what goes wrong, using [echo g | hid-keyboard /dev/hidg0 keyboard] works fine tho...
the reason why I back to use x00 method is because the speed the strings output from latest NH version is a bit slow, and I can't find out how to speed up.

Okay, I just tested out that it successfully output `g` when executing `echo -ne "\x00\x00\x00\x0a\x00\x00\x00\x00" > /dev/hidg0` in android environment, but failed in kali environment.
so strange....only happens to the letter `g`..

**Comment by simonpunk** [comment]
Now I just made a temp solution for me. I changed to also create a copy of `(kali)/opt/duckout.sh` to `(android)/data/local/tmp/`, and it executes the duckout.sh in andriod env instead of kali env. 
Now should be working fine for me..although it seems not to be a good idea doing this way.
