### ISSUE TITLE
postgresql serveice start fail from Kali chroot

### ISSUE THREAD

**Issue by TomasAndersonvoid** [offensive-security/kali-nethunter#374]
I am using Nexus6p with stock android 6.0 ROM and the new nethunter
I was trying to start postgresql service and link it with MSF and I was following the stage:
//Start the Postgresql Database
/etc/init.d/postgresql start

//Initialize the Metasploit Framework Database
msfdb init

//Run msfconsole
msfconsole

However there is an error occur. The postgreSQL server failed to start. Please checck the log output:....

FATAL: could not create shared memory segment: Function not implemented ..

Any help plz

**Comment by binkybear** [comment]
Is the correct kernel installed?

**Comment by TomasAndersonvoid** [comment]
I think yes, other function works fine, the version is 3.0.1 2016-1-10.

**Comment by binkybear** [comment]
If you go to settings > about does it says root@kali in kernel version.

**Comment by TomasAndersonvoid** [comment]
yes: 3.10.94+ root@kali num.3 wed jan 6

**Comment by binkybear** [comment]
I think that might be old one since you seem to be missing systemvipc, I uploaded new one on Jan 11.  Maybe try flashing new one again in recovery.  You can build yourself or use this one from jcad:

https://idlekernel.com/nethunter/nightly/3.0.5-20160202-2121/kernel-only/kernel-nethunter-bullhead-marshmallow-3.0.5-20160202-2121.zip

**Comment by TomasAndersonvoid** [comment]
Thanks binky, it works now.
