### ISSUE TITLE
Error running Kali Terminal

### ISSUE THREAD

**Issue by calebbait** [offensive-security/kali-nethunter#412]
**Device:** Moto E LTE 2015
**ROM:** CyanogenMod 13.0 (Android 6.0.1)
When I try to launch the Kali Terminal, it flashes some errors (see screenshots below) then closes. Android and AndroidSU both seem to be working fine. All terminals have no title.
I noticed an error when flashing the Nethunter zip that said something along the lines of "failed to patch boot image" everything else executed successfully. I've reflashed CM+Nethunter three times with the same result each time.

(apologies for the odd screenshots, had to use CM's screencast to record the errors as they went by too quickly to screenshot on their own)
![screenshot_20160326-003315](https://cloud.githubusercontent.com/assets/13278641/14058067/96a8c59a-f2ea-11e5-8945-0f741f93c1dd.png)
![screenshot_20160326-003324](https://cloud.githubusercontent.com/assets/13278641/14058066/967ce178-f2ea-11e5-8ff2-b5fc7c89d70f.png)

**Comment by binkybear** [comment]
You appear to be missing a chroot and your kernel doesn't support shmmax.  Did you build installer from github?

**Comment by jcadduono** [comment]
if you built from yesterday's sources (after https://github.com/offensive-security/kali-nethunter/commit/aa967fdf5e92d4acd750a172c2b336cb49d25449) and are using multirom then you will have run into the failed to patch boot image issue, i fixed some hours later.

if you're still having issues with "failed to patch boot image" can you please upload your recovery.log after trying to flash?
you can get that from:
adb pull /tmp/recovery.log
or you can go to advanced -> copy log to sdcard in twrp and it will be in your sdcard or internal storage.

there may be some things i need to resolve with twrp's flash_image / dump_image feature.

**Comment by calebbait** [comment]
@binkybear Yeah, I built the installer from Github. I can provide me devices.cfg if needed.
@jcadduono I actually built it a few days ago. I'm not using multirom, but I'll try rebuilding from the newer sources and see if that helps.

If there is any other information I could provide that might help, just let me know. I'm fairly new to Linux and messing around with Android kernels and stuff.

**Comment by calebbait** [comment]
[recovery.log](https://github.com/offensive-security/kali-nethunter/files/190589/recovery.log.txt)
It still failed, here is my recover.log file.

**Comment by jcadduono** [comment]
your log seems to have cut off while extracting, perhaps there is an issue with your twrp build...did it cut off that early in the actual flash? (ex. did it fail while extracting too?)
you might need to build without the kalifs if so, because your device only has 1 GB ram and you may have run out of space. TWRP loads the entire zip contents into RAM and then needs more for extracting to the storage, etc.
in rare cases this happens, you can take the kalifs tar.xz out of the installer and instead, `adb push kalifs-*.tar.xz /data/local/` before installing. the installer will use that if it finds it.

**Comment by calebbait** [comment]
@jcadduono The only error I got during flash was the "failed to patch boot image" one. 
I'll try the suggestion with taking the kalifs out and loading it into /data/local/
If I still have issues then, I'll try updating TWRP and see if that helps anything. 
I'm rather new to github, so please excuse my ignorance, but what is a git rebase?

**Comment by jcadduono** [comment]
basically, how you are supposed to work with github, is you first fork somebody elses project, like kali-nethunter using the fork button on github.
then you clone it to your pc, like so:
`git clone https://calebbait@github.com/calebbait/kali-nethunter.git`
then enter the project folder, and add us as an upstream, ex.
`git remote add ofsc https://calebbait@github.com/offensive-security/kali-nethunter.git -t master`
now, whenever we make a change, you can do
`git fetch ofsc`
followed by
`git rebase ofsc`
git will then magically take all of your commits and put them on top of our current work, bringing you up to date!
alternatively, you can cherry-pick instead of rebase our commits to keep the timeline and not have to force push your work.

**Comment by calebbait** [comment]
After moving the kalifs to `/data/loca/`, the boot image patched successfully, but I'm still having issues with the terminal.
[updated recovery.log](https://github.com/offensive-security/kali-nethunter/files/190620/recovery.log.txt)

**Comment by jcadduono** [comment]
if you read your recovery.log it actually says you ran out of space on your data partition lol =) (the chroot is 2.3 GB!!)

**Comment by calebbait** [comment]
@jcadduono Ah lol, I'll see if I can clear up some space.

**Comment by 0E800** [comment]
I appreciated the troubleshooting workflow and the git lesson. Happy Easter
to the devs and their families .

**Comment by jcadduono** [comment]
happy easter to you and all our users and their families as well! it's actually my birthday today too lol :P i need to get up off the github and go party!

**Comment by calebbait** [comment]
Seems like my internal storage just isn't big enough :(
Is there any way to install Nethunter onto an external SD?

**Comment by jcadduono** [comment]
8 GB of internal storage should leave you at least 4 GB.
It isn't currently possible to install the chroot to an external SDcard due to mounting issues (storage is mounted differently than data on most devices, making unix permissions broken)
I recommend using a minimal chroot for now, and adding packages as you need them.
You can do this with --rootfs minimal, or don't include one and have the nethunter app install it, or build your own from kali-rolling using nethunter-fs/build.sh (only recommended on debian and kali), or simply use the prebuilt nightly generics, ex.
https://idlekernel.com/nethunter/nightly/3.0.5-20160326-0309/chroot-minimal/update-nethunter-generic-armhf-kalifs-minimal-rolling-3.0.5-20160326-0309.zip
will install the minimal chroot for you.

**Comment by calebbait** [comment]
@jcadduono After a clean CM13+Gapps Nano install, I'm left with about 3.5GB. When I flash Nethunter, I get the "ran out of space error." and am still left with the same issue with the terminal as before. When I check my free space after flashing, I'm at about 660MB.

**Comment by calebbait** [comment]
Installing the chroot minimal package from the Nethunter app worked, closing the issue. Thanks for all the help.

**Comment by suhancz** [comment]
A tiny workaround I just tested - you may need [Link2SD](https://play.google.com/store/apps/details?id=com.buak.Link2SD) set up with a separate ext partition for the task. Just run the following script on your Android device as root.
[move_nethunter_to_link2sd_second_partition.sh](https://github.com/offensive-security/kali-nethunter/files/560446/move_nethunter_to_link2sd_second_partition.txt)
