### ISSUE TITLE
Can we delete kalifs-full.tar

### ISSUE THREAD

**Issue by tibas21** [offensive-security/kali-nethunter#443]
Hello!
I'v installed nethunter with succes, and everythings seems ok.
I have a file named "kalifs-full.tar" 2.02GB. I don't know if it's still necessary or not (2gb free space could be very nice !)
Can i delete it ?
Thanks for yours answers
Tibas

**Comment by jcadduono** [comment]
Yup! You may delete it without any issues. I caution you that 2.02 GB is 20 MB of things that might be missing from your chroot, as currently the NetHunter app calls to OS busybox which is unable to read files past 2.00 GB! The reason it's still there is probably due to tar crashing at 2.00 GB mark and error going unhandled, resulting in chroot tar still being there. (in case you need to retry would be one reason to keep it...)
