### ISSUE TITLE
Nexus 6p release

### ISSUE THREAD

**Issue by Bascard** [offensive-security/kali-nethunter#451]
Have u any idea when nethunter will officialy get released

Sry for bad english, english isn't my mother language

**Comment by jmingov** [comment]
Hello @Bascard, we support the device since a few months ago, but you need to build it yourself.

Steps to build are here: https://github.com/offensive-security/kali-nethunter/wiki#30-building-nethunter.


Your device-name is: angler

Sources are here: https://github.com/offensive-security/kali-nethunter/blob/master/kernels.txt#L25


BR 

Jaime
