### ISSUE TITLE
oneplus one: temporarly failure resolving 'repo.kali.org'

### ISSUE THREAD

**Issue by xavkno** [offensive-security/kali-nethunter#454]
After using apt-get upgrade I am having a problem with apt-get update.

This is the output from apt-get update:

http://pastebin.com/5cKrM9sY

Thanks in advance.

**Comment by pyc0de** [comment]
Having the same issue on CM13 Nexus7 deb after switchng to kali-rolling repo.
tried thkis solution: 
https://bugs.kali.org/view.php?id=3012
but still get this:
# apt-get update
 Err:1 http://http.kali.org/kali kali-rolling InRelease
  Could not connect to http.kali.org:80 (192.99.200.113). - connect (111: Connection refused)

Shouldn't  it be fixed already?
And why Nethunter still uses sana repo?

**Comment by pyc0de** [comment]
Having the same issue on CM13 Nexus7 deb after switchng to kali-rolling repo.
tried thkis solution: 
https://bugs.kali.org/view.php?id=3012
but still get this:
# apt-get update
 Err:1 http://http.kali.org/kali kali-rolling InRelease
  Could not connect to http.kali.org:80 (192.99.200.113). - connect (111: Connection refused)

Shouldn't  it be fixed already?
And why Nethunter still uses sana repo?

**Comment by pyc0de** [comment]
Having the same issue on CM13 Nexus7 deb after switchng to kali-rolling repo.
tried thkis solution: 
https://bugs.kali.org/view.php?id=3012
but still get this:
apt-get update
 Err:1 http://http.kali.org/kali kali-rolling InRelease
  Could not connect to http.kali.org:80 (192.99.200.113). - connect (111: Connection refused)

Shouldn't  it be fixed already?
And why Nethunter still uses sana repo?

**Comment by jcadduono** [comment]
if you don't mind losing your current chroot, you can replace it with a fresh rolling chroot, as well as upgrade to nethunter 3.1.0 (still pre-release) by flashing:
https://idlekernel.com/nethunter/nightly/3.1.0-20160519-1931/update-nethunter-generic-armhf-3.1.0-20160519-1931.zip
you can also extract the prebuilt chroot from that zip and install it with the nethunter app from placing the .tar.xz on your sdcard/internal storage.

otherwise, you can git clone this repository and use the build scripts in the nethunter-fs folder to build yourself a new kali rolling chroot.

i don't have a solution to your connection refused issue besides starting fresh. it can be fixed though if you wait around for @binkybear to respond, he surely knows more than i in this area.

**Comment by pyc0de** [comment]
should I remove existing chroot first from within nethunter app, or I could just flash update over it?
ps: this update contains new versions of nethunter and terminal apps too, right?
thanks!

**Comment by xavkno** [comment]
How can i extract the prebuilt chroot from the archive

**Comment by binkybear** [comment]
The error you are receiving is because you updated to kali-rolling inside chroot.  If you used our builder it should have been fixed:
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-fs/stages/stage3#L100

So you run that command inside your chroot:
```bash
sed -i 's/_apt:x:104:65534/_apt:x:104:3004/g' /etc/passwd
```
What happened here is that in debian/apt there is a new _apt user that handles getting updates.  It needs to be added to Android's INET group so that it can access the network.

**Comment by pyc0de** [comment]
Thanks, did that and it appears that AFwall+ is blocking kernel (uid: -1).
This was not the case on NH2 + Kitkat. Is this change  attributed to NH3.1 or to CM13/Android  M?
Guess I have to use cusdtom script to witelist http.kali.org in AFwall.

**Comment by pyc0de** [comment]
Thanks, did that and it appears that AFwall+ is blocking kernel (uid: -1). So I still get connection refused while running apt-get update.
This was not the case on NH2 + Kitkat. Is this change  attributed to NH3.1 or to CM13/Android  M?
Guess I have to use cusdtom script to witelist http.kali.org in AFwall.

**Comment by pyc0de** [comment]
Thanks, did that and it appears that AFwall+ is blocking kernel (uid: -1). So I still get connection refused while running apt-get update.
This was not the case on NH2 + Kitkat. Is this change  attributed to NH3.1 or to CM13/Android  M?
Guess I have to use cusdtom script to witelist http.kali.org in AFwall.

**Comment by pyc0de** [comment]
Thanks, did that and it appears that AFwall+ is blocking kernel (uid: -1). So I still get connection refused while running apt-get update.
This was not the case on NH2 + Kitkat. Is this change  attributed to NH3.1 or to CM13/Android  M?
Guess I have to use cusdtom script to witelist http.kali.org in AFwall.

**Comment by pyc0de** [comment]
set this custom script in afwall+:

IPTABLES=/system/bin/iptables
APT_UID=104
$IPTABLES -A afwall-wifi -m owner --uid-owner $APT_UID -j ACCEPT || exit
