### ISSUE TITLE
Bluetooth attacks

### ISSUE THREAD

**Issue by Zahkc** [offensive-security/kali-nethunter#456]
Hey all

Just wondering if there is any support for Bluetooth attacks. I got a UD100a sena Bluetooth adapter and i realized that the Bluetooth service wouldn't stay on, there for rendering hciconfig null. I am wondering is there is a fix im not noticing or if its a planned feature or whatever. Also integrated bt didnt work either (wasn't expecting it to -_-).

Thanks
    ~Zahkc

**Comment by Dr0me** [comment]
Is it possible for nethunter to take use internal Bluetooth?  With Bluetooth on I am not able to get any hciconfig returns

**Comment by binkybear** [comment]
No you won't be able to access using internal bluetooth.  You will probably want to look at using something like ubertooth or a similar tool.  Also, the kernel needs to have enabled support for those bluetooth devices (external).

**Comment by Zahkc** [comment]
How would I enable support on the kernel? I've seen it done with the same adapter on a nexus 5 and was wondering if it was a hard process?

**Comment by yesimxev** [comment]
Have you ever solved this issue? @Zahkc 
I have gone to the point where btusb is enabled in the kernel for external bluetooth, with rfcomm, and all possibilites, but never worked fully. With bluez <5, service stays on but SCO socket can't be created, with bluez >5 btmgmt socket can't be created. Seems like the device is not capable, because it runs in chroot before putting onto the device.

Kind of full story: 
https://github.com/offensive-security/kali-nethunter/issues/1171
