### ISSUE TITLE
Oneplus one builds to cm13?

### ISSUE THREAD

**Issue by pahapoika** [offensive-security/kali-nethunter#458]
Would someone be so kind and build for oneplus one. To cm13 and cos13 or atleast to cm13. 
If  you have already built could you share download link. 
Thanks.

**Comment by bkr32** [comment]
you can simply flash the update package found on here  https://idlekernel.com/nethunter/nightly/3.0.5-20160421-0440/  and install chroot through the nethunter app

**Comment by neyromanser** [comment]
Thank U very much! Had a crazy week trying to install CM13 on marshmallow. Main reason because on CM12 NetHunter freeze very often. The original CM13 kernel that comes with current LRT work very well except Y-cable not charge (already know that it is firmware bug) and another very annoying bug - battery indicator always show 100% (coz healthd can't find type file in sys/class... buttery dir). So I had try binkybear last CAF kernel https://github.com/binkybear/AK-OnePone/tree/cm-13.0-caf. It fix battery problem, but camera stop working. Last nightly kernel (2330) have buttery issue as first one. Also try to build kernel with other config, with no luck... And eventually this kernel solve both bugs, again many thanks and great respect to all of NetHunter devs!)

**Comment by bkr32** [comment]
this kernel has no issues https://idlekernel.com/nethunter/nightly/3.1.0-20160429-0011/
except y-cable , there is a update that i'm trying out now

**Comment by xtr4nge** [comment]
Hi bk32,
I tried that kernel (3.1.0-20160429-0011) but the battery issue still present.

Just for reference, I already tried with:
3.1.0-20160429-0011
3.1.0-20160524-0111
3.1.0-20160524-1936

I finally installed 3.0.5 again, as the battery status is displayed correctly: **3.0.5-20160425-1720**

**Note**: I'm using  [cm-13.0-20160419-SNAPSHOT-ZNH0EAO2O0-bacon](https://download.cyanogenmod.org/get/jenkins/158663/cm-13.0-20160419-SNAPSHOT-ZNH0EAO2O0-bacon.zip)
regards,

**Comment by bkr32** [comment]
@xtr4nge sorry for providing the wrong kernel, the bug has been present for a while and i lost track as well, but as of now that is the best kernel to use

**Comment by evilsperm** [comment]
Can someone please upload 3.0.5-20160421-0440 because its gone form the idealkernel nightlies.

**Comment by bkr32** [comment]
@evilsperm https://github.com/offensive-security/kali-nethunter/issues/485

**Comment by miquelcopet** [comment]
hey the link seems to be down :/

**Comment by bkr32** [comment]
for kernel or build? @miquelcopet
