### ISSUE TITLE
not clear how to maintain up-to-date Nethunter installation

### ISSUE THREAD

**Issue by pyc0de** [offensive-security/kali-nethunter#459]
Hi,
How should I go with updates to CM and NH?
1. NH
as I understand I should flash zips from here?
https://idlekernel.com/nethunter/nightly/
I should reflash kernel, do I need to reflash  chroot also?
what is update-nethunter-generic...zip for?

2. After I flash CM nightly should I just reflash NH kernel or this is not  enougth?

Please help, I'm confused. Been using Binky's pawnpad but with NH all becomes more complex and it just drowns in issues.(

Thanks.

**Comment by bkr32** [comment]
well after installing the update pack you can simply apt-get update && apt-get upgrade to keep packages up to date, flash the latest kernel whenever you see a commit made for it and flash any new nethunter version when it becomes available

**Comment by jcadduono** [comment]
expanding on that, for fresh installations i recommend flashing both:
nethunter-generic-armhf-kalifs-full-rolling-*.zip
kernel-nethunter-yourdevice-yourandroidversion-*.zip

if you update your rom, you will need to flash:
update-nethunter-generic-armhf-*.zip (everything except chroot, since you still have it)
kernel-nethunter-yourdevice-yourandroidversion-*.zip (rom updates replace your kernel, so you need to flash this again)

should you wish to reset your entire nethunter install back to fresh, then you can flash the kalifs-full zip.

**Comment by xavkno** [comment]
I can't find the nethunter-generic-armhf-kalifs-full-rolling-*.zip 

Could you please provide a link to it.

Thank you in advance.

**Comment by pyc0de** [comment]
https://idlekernel.com/nethunter/nightly/3.1.0-20160524-1936/nethunter-generic-armhf-kalifs-full-rolling-3.1.0-20160524-1936.zip
