### ISSUE TITLE
Kernel Compiling Bluetooth error

### ISSUE THREAD

**Issue by semsevens** [offensive-security/kali-nethunter#467]
I'm trying to modify and build a new kernel for Samsung S4.

I just do it like here.

But when I make, I ran into some problems:

Code:
`
drivers/bluetooth/btusb.c: In function '__check_ignore_dga':
drivers/bluetooth/btusb.c:1231:1: warning: return from incompatible                  pointer type [enabled by default]
error, forbidden warning: btusb.c:1231
scripts/Makefile.build:307: recipe for target     'drivers/bluetooth/btusb.o' failed
make[2]: *** [drivers/bluetooth/btusb.o] Error 1
scripts/Makefile.build:443: recipe for target 'drivers/bluetooth'  failed
make[1]: *** [drivers/bluetooth] Error 2
Makefile:973: recipe for target 'drivers' failed
make: *** [drivers] Error 2
`

I have google the problem for a couple hours, but can't find any solution yet.

What do I need to do to fix this?

**Comment by jcadduono** [comment]
in btusb.c around line 1231 theres probably a module_param declaration of ignore_dga as a boolean toggle, but ignore_dga is probably declared near the top of the file as an integer designed for 1 or 0 choices. change it to a bool, so like bool ignore_dga = false; instead of int ignore_dga = 0; for example

**Comment by semsevens** [comment]
@jcadduono 
Thank you very much.
It solves my problem.

**Comment by 0E800** [comment]
Thank you. Another build breadcrumb added to bookmarks.
