### ISSUE TITLE
marshmallow for grouper

### ISSUE THREAD

**Issue by harayz** [offensive-security/kali-nethunter#487]
may i know why grouper does not have marshmallow kernel?

**Comment by binkybear** [comment]
The short answer is because Google ended support for Nexus 7 2012 at lollipop.  

I know there are "unofficial" marshmallow builds but Grouper is starting to lack memory and is low on system space. If I were to make a kernel it would be from an official CM build but I noticed it's still on lollipop also.

**Comment by harayz** [comment]
yes, i agree. thank you for sharing. now it is clear to me why and i can start look around for a new device. appreciate your respond and thank you for all that you've done here. good job and keep it up!
