### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by DarrenRainey** [offensive-security/kali-nethunter#499]
I am unable to install nethunter on my nexus 5 I have tried multiple versions of android and nethunter and all freeze at install and cause problems after booting such as system ui not repsonding and crashes any ideas I've used the latest version of twrp 3.0 and android 5.0 as well and 6.0 and cyanogenmod 13

**Comment by pyc0de** [comment]
give us some details, logs, etc.

**Comment by jcadduono** [comment]
not really a valid issue with it being related to bugs fixed since 3.0.1+
you should consider building a new installer from git sources (see readme.md in nethunter-installer folder)
you can also download untested automatically generated builds from idlekernel.com/nethunter/nightly (you need a kernel-nethunter zip and a nethunter-generic-armhf zip)
