### ISSUE TITLE
I got a system update msg... can i do it? or what should I do?

### ISSUE THREAD

**Issue by ChrisFernandez** [offensive-security/kali-nethunter#515]
Hello sorry for the lame question, I only saw very old responses from first versions of nethunter and cyanogenmod..
so I keep getting the pop to update android... is safe to do so? or how are we supposed to keep updated, it may be security fixes..

**Comment by binkybear** [comment]
If you update with OTA it will kill Nethunter (but it probably won't work anyways because you have TWRP installed).  If you need to update you will have to either find someone that made a flashable OTA for TWRP or reflash factory.  Then you would have to reinstall NH.

So it can difficult to keep up with OTAs.

**Comment by ChrisFernandez** [comment]
thanks for the your response, I really appreciate it.. do people usually come upo with flashable OTA for TWRP? in any case, how do I disable the OTA notification then? so at least is not annoying

**Comment by binkybear** [comment]
How to disable: https://www.youtube.com/watch?v=uG74kzUTLl8

Some people will upload flashable OTA's but you need to check XDA forums.  Otherwise it's best to just disable.

**Comment by ChrisFernandez** [comment]
@binkybear thanks.. sorry took me a while to reply..
is there a newer version of nethunter for nexus 5x yet? I still have the same from July.
feel free to close this after a response.

**Comment by ChrisFernandez** [comment]
closing this..
