### ISSUE TITLE
Aireplay-ng exited unexpectedly

### ISSUE THREAD

**Issue by gooldennn** [offensive-security/kali-nethunter#519]
using wifite on nethunter im getting 
Attack failed: aireplay-ng exited unexpectedly, im also getting, attack failed: unable to generate keystream.
Any idea on how to get this working?

**Comment by simonblack** [comment]
This is an issue with the way wifite reads the mac address. Using the patch in this thread worked for me: https://github.com/Akash786mrn/wifite/issues/82

Note: I had to apply it manually presumably due to other fixes in my wifite.py. You may have to patch manually as well (outdated patch?) by adding the import statement around line 77 and changing the entire get_mac_address method (~line 1940  for me) to the method defined in the patch.

Mac adress method source: http://code.activestate.com/recipes/439094-get-the-ip-address-associated-with-a-network-inter/

**Comment by gooldennn** [comment]
Hi.thanks for the replay.
Tryed to change the cmd = aireplay as the guide said on my computer without luck, dint not change the mac addreds method tho.
Anyway, im having truble opening text files on my mobile where i have nethunter installed. any ideas on how to change code on the cellphone? Ive tryied the apt-get install gedit but dint not seem to work on the phone.
cd /usr/bin/wifite.(py) 
Thanks for any help i can get

**Comment by vay3t** [comment]
u can use sftp (like a ssh. u need start ssh in nethunter) use command put for upload files.

**Comment by gooldennn** [comment]
thanks @vay3t 

@simonblack 
When im looking at the get_mac_address.patch it seems to be the same code that i have in my wifite.py

If anyone could upload a wifite.py that are working with alfa awus036h, that would be great

**Comment by binkybear** [comment]
@gooldennn - You could give mine a try: https://raw.githubusercontent.com/binkybear/wifite-mod-pixiewps/master/wifite-ng

**Comment by gooldennn** [comment]
Thanks @binkybear i have not had the time to test it yet, but its much appresiated!

**Comment by gooldennn** [comment]
Will give feedback as soon as i have tried it out

**Comment by gooldennn** [comment]
Gave it a shot now, seemed to be working fine! thanks @binkybear you're the man!
