### ISSUE TITLE
suggestion: universal serial abuse

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#599]
interesting and powerful modality would implement 'universal serial abuse' in nethunter hid. versatility without suspicion. a form of social engineering to scam the victim is that the phone is charging

**Comment by binkybear** [comment]
https://www.sensepost.com/blog/2016/universal-serial-abuse/
https://github.com/sensepost/USaBUSe
https://www.youtube.com/watch?v=5gMvtUq30fA

**Comment by bkr32** [comment]
was going through how this works,they used a modified ducky script to execute payload when they want to, the networking device is attached to the usb and creates a vnc server that;s accessed via vncdo.

guess i'll need some help getting this to work mainly since hostapd doesn't work by default on wlan0,
@binkybear would you know a way around this? and can ducky scripts be executed via terminal ?

**Comment by binkybear** [comment]
Hey bkr32,

Ducky scripts could be executed in the terminal:
```
bootkali duck-hunt-run /opt/duckout.sh
```
That's assuming you converted one of the duckyscripts to its shell output.
```bash
bootkali duck-hunt-convert us /sdcard/nh_files/modules/duckconvert.txt /opt
```
The above will generate the /opt/duckout.sh.  The above commands must be run outside the chroot (androidsu).

As far as hostapd not working on wlan0 I'm not sure if there is a way around that, would have to research that more.

**Comment by bkr32** [comment]
i ended up following this https://github.com/byt3bl33d3r/duckhunter
although for some reason its pretty slow while typing out, i'll switch to the bootkali method
switched out vncdo for ssh because its a lot easier to control and navigate 
still haven't found anything on hostapd except that it requires a driver name so probably quallcom 801 drivers 
lastly having issues typing out the exec file that provides the shell
