### ISSUE TITLE
Not detect Tplink 722 and alfa wifi card

### ISSUE THREAD

**Issue by pindonga1234** [offensive-security/kali-nethunter#646]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

h

**Comment by PurvC** [comment]
Must be that your OTG adapter might not be working. Test it by inserting a pendrive or a mouse or any other device.

**Comment by pindonga1234** [comment]
I did it, with a pendrive works very well, but with the wifi card not.

**Comment by akrolla** [comment]
Dmesg | grep usb paste a photo of the log or what it says. Glad to be  of
service.

On Oct 31, 2016 7:01 PM, "pindonga1234" <notifications@github.com> wrote:

I did it, with a pendrive works very well, but with the wifi card not.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/646#issuecomment-257455399>,
or mute the thread

**Comment by pindonga1234** [comment]
Thank for help me again akrolla
[ 2312.062033] usb 1-1: Product: USB2.0 WLAN
[ 2312.062184] usb 1-1: Manufacturer: ATHEROS
[ 2312.062449] usb 1-1: SerialNumber: 12345
[ 2312.380215] usb 1-1: USB disconnect, device number 91
[ 2312.646142] active wakeup source: smb347-usb
[ 2313.532635] usb usb1: USB disconnect, device number 1
[ 2320.667148] android_usb gadget: high-speed config #1: android
[ 2326.565867] android_usb: already disabled
[ 2326.904702] android_usb gadget: high-speed config #1: android
[ 2375.836276] android_usb: already disabled
[ 2376.270744] android_usb gadget: high-speed config #1: android
[ 2505.055541] usb_phy: failed to get regulator vdd_vbus_usb:-517,instance : 0
[ 2506.071048] SELinux: initialized (dev usbfs, type usbfs), uses genfs_contexts
[ 2506.105897] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[ 2506.105980] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 2506.106151] usb usb1: Product: Tegra EHCI Host Controller
[ 2506.106233] usb usb1: Manufacturer: Linux 3.4.67-gc3287cd ehci_hcd
[ 2506.106364] usb usb1: SerialNumber: tegra-ehci.0
[ 2506.408622] usb 1-1: new high-speed USB device number 2 using tegra-ehci
[ 2506.439393] usb 1-1: New USB device found, idVendor=148f, idProduct=3070
[ 2506.439473] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2506.439625] usb 1-1: Product: 802.11 n WLAN
[ 2506.439699] usb 1-1: Manufacturer: Ralink
[ 2506.439824] usb 1-1: SerialNumber: 1.0
[ 2567.095351] usb 1-1: USB disconnect, device number 2
As you can see, kali detect very well the tp-link 722 n, the alfa 036nh but not the alfa 036h, but doesnt matter the last one if it not work. But the fact is that when I use wifite not detect wlan1 and when I do ifconfig neither

**Comment by akrolla** [comment]
I try I'm still learning like you @binkybear and jcadduono there the real
geniuses behind this. are you using a otg cable or y cable with a battery.
I'm not sure if the usb alone can support that antennae without the help of
y cable charging.
On Nov 1, 2016 9:17 PM, "pindonga1234" <notifications@github.com> wrote:

>

> >

> Thank for help me again akrolla
> [ 2312.062033] usb 1-1: Product: USB2.0 WLAN
> [ 2312.062184] usb 1-1: Manufacturer: ATHEROS
> [ 2312.062449] usb 1-1: SerialNumber: 12345
> [ 2312.380215] usb 1-1: USB disconnect, device number 91
> [ 2312.646142] active wakeup source: smb347-usb
> [ 2313.532635] usb usb1: USB disconnect, device number 1
> [ 2320.667148] android_usb gadget: high-speed config #1
<https://github.com/offensive-security/kali-nethunter/issues/1>: android
> [ 2326.565867] android_usb: already disabled
> [ 2326.904702] android_usb gadget: high-speed config #1
<https://github.com/offensive-security/kali-nethunter/issues/1>: android
> [ 2375.836276] android_usb: already disabled
> [ 2376.270744] android_usb gadget: high-speed config #1
<https://github.com/offensive-security/kali-nethunter/issues/1>: android
> [ 2505.055541] usb_phy: failed to get regulator
vdd_vbus_usb:-517,instance : 0
> [ 2506.071048] SELinux: initialized (dev usbfs, type usbfs), uses
genfs_contexts
> [ 2506.105897] usb usb1: New USB device found, idVendor=1d6b,
idProduct=0002
> [ 2506.105980] usb usb1: New USB device strings: Mfr=3, Product=2,
SerialNumber=1
> [ 2506.106151] usb usb1: Product: Tegra EHCI Host Controller
> [ 2506.106233] usb usb1: Manufacturer: Linux 3.4.67-gc3287cd ehci_hcd
> [ 2506.106364] usb usb1: SerialNumber: tegra-ehci.0
> [ 2506.408622] usb 1-1: new high-speed USB device number 2 using
tegra-ehci
> [ 2506.439393] usb 1-1: New USB device found, idVendor=148f,
idProduct=3070
> [ 2506.439473] usb 1-1: New USB device strings: Mfr=1, Product=2,
SerialNumber=3
> [ 2506.439625] usb 1-1: Product: 802.11 n WLAN
> [ 2506.439699] usb 1-1: Manufacturer: Ralink
> [ 2506.439824] usb 1-1: SerialNumber: 1.0
> [ 2567.095351] usb 1-1: USB disconnect, device number 2
> As you can see, kali detect very well the tp-link 722 n, the alfa 036nh
but not the alfa 036h, but doesnt matter the last one if it not work. But
the fact is that when I use wifite not detect wlan1 and when I do ifconfig
neither
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/646#issuecomment-257753957>,
or mute the thread

**Comment by pindonga1234** [comment]
I use that without a battery, with a OTG cable. It is a sofware problem because with the old release nethunter 3.0 downloaded from kali page for grouper, boards works very well both

**Comment by akrolla** [comment]
are the drivers in the minimal chroot? im not sure

**Comment by akrolla** [comment]
and also @pindonga1234 what 3.4 kernel did you end up using

**Comment by pindonga1234** [comment]
Thank akrolla I need to help, there was a long time nobody can help me. Well I say you that becauses nothing worked I erased the rom that had the 3.4 kernel, but I finded a file that have 3.2.56 kernel, I puted it in CM12 and works very well. Second I dont have the more minimal idea where goes the firmware folder in the minimal chroot. I was looking for in the nethunter 3.0 downloaded from kali site and that minimal chroot neither had it. I only finded in the nethunter 3.0 a folder /system/etc a folder firmware, I putted it in the generic armfh nethunter, but didnt work, also I putted in /data/local/nhsystem/kali-armhf/system/etc the folder firmware but didnt work neither. This thing that write in english is very difficult for me ha ha, I have to return to the classroom. In fact Ive never liked english, but it is a international languague so you need to learn it if you wanna communicate with the world

**Comment by akrolla** [comment]
I think the atheros firmware has to go in sys/bin of android su I'm not
sure @binkybear? There some more issues on here pertaining to it I believe
that was the solution they came up with, try to look through the issues and
see anything about missing dongle firmware.

On Nov 29, 2016 7:40 AM, "pindonga1234" <notifications@github.com> wrote:

Thank akrolla I need to help, there was a long time nobody can help me.
Well I say you that becauses nothing worked I erased the rom that had the
3.4 kernel, but I finded a file that have 3.2.56 kernel, I puted it in CM12
and works very well. Second I dont have the more minimal idea where goes
the firmware folder in the minimal chroot. I was looking for in the
nethunter 3.0 downloaded from kali site and that minimal chroot neither had
it. I only finded in the nethunter 3.0 a folder /system/etc a folder
firmware, I putted it in the generic armfh nethunter, but didnt work, also
I putted in /data/local/nhsystem/kali-armhf/system/etc the folder firmware
but didnt work neither. This thing that write in english is very difficult
for me ha ha, I have to return to the classroom. In fact Ive never liked
english, but it is a international languague so you need to learn it if you
wanna communicate with the world

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/646#issuecomment-263572429>,
or mute the thread

**Comment by pindonga1234** [comment]
Thanks akrolla for reply my question, the path in android is sys/firmware, but there is not chance to copy anything in this folder. I tried by adb terminal giving all permission +xwr and I couldnt copy or remove the folder it is impossible to do it, I tried by TWRP with the file manager but I couldnt do it, everything I did gave me error. I tried to copy in CM11 ROM in /system/etc/firmware all the files but they didnt copy in sys/firmware android path. Any solution?

**Comment by akrolla** [comment]
In android su or android

**Comment by pindonga1234** [comment]
Do you a app?, because I opened the nethunter terminal and choiced android su and I couldnt do it

**Comment by jcadduono** [comment]
you can't use wireless cards unless their drivers are enabled in the kernel. you need a kernel that is both 3.4 AND has wireless drivers and packet injection patched and enabled in it - firmware is not enough (firmware is installed by any nethunter zip!)

**Comment by pindonga1234** [comment]
I couldnt understand so mucho, so I cant use the generic nethunter on my devices?

**Comment by jcadduono** [comment]
generic zips are for use with nethunter kernels, you cannot use ANY otg features without being supported by nethunter
