### ISSUE TITLE
Ethernet HID 

### ISSUE THREAD

**Issue by bkr32** [offensive-security/kali-nethunter#649]
### Device:

OnePlus One
## Issue:

i was looking through [https://room362.com/post/2016/snagging-creds-from-locked-machines/](this)
and wondered if it can be replicated in nethunter for the most part its possible however the only difference between the armor usb and turtle is that nethunter doesnt seem to have a ethernet HID,
is it possible to add that?

**Comment by nethunteros** [comment]
It actually should be in the latest nethunter-utils package so you might have it in your /usr/bin/mubix-lock.sh

Code is here:
https://github.com/offensive-security/nethunter-utils/blob/master/usr/bin/mubix-lock.sh

It assumes an rndis0 which should be on most newer Android devices.  I have test on ONePlus1 and it works fine.

**Comment by bkr32** [comment]
thanks for the heads up lemme give it a try

**Comment by binkybear** [comment]
You should see NTLMv2 hashes in the screen -r.  Those should also save to a sql db in responder and I believe an output log.  Those hashes you would need to run through a cracking program like oclHashcat.

As far as "NethunterOS" right now it's just me experimenting between AOSP and CM to build everything Nethunter uses into a ROM instead of an update file.  I don't even have a working build yet.

**Comment by bkr32** [comment]
well besides poisoned replies i dont see anything, 
still see poisoned replies and occasionally my OS version
how long did it take you for the hashes to show up?
i'm running insider build 14936

i think a cm based rom would work out for NOS, 
hope i can contribute to it in some way
