### ISSUE TITLE
Nethunter Kernel not booting on Oneplus One CM13. What is the problem? 

### ISSUE THREAD

**Issue by BZBaXraM** [offensive-security/kali-nethunter#693]
What is the problem?

**Comment by Zarkopafilis** [comment]
Same thing here. Ended up installing cm 12.1 (Android 5.1), also updating kernel to version 5.0 (I did these together so I don't know wether one of these 2 was the issue, but my guess is probably the latter because the wiki suggests that it works). Previous kernel version was 3.4.something but it didn't work.

On the other hand, I also manually installed/updated busybox, but also got MultiRom installed (this updated my kernel too). My installation with this 12.1 hanged at first boot but I was able to reboot correctly and install the 3 apps manually
