### ISSUE TITLE
bootkali command doesn't detect Busybox

### ISSUE THREAD

**Issue by Dracer0185** [offensive-security/kali-nethunter#695]
### Device: 

HTC One A9

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow 6.0.1

### Built from repo (date and build command) or downloaded from website (links):

From official Website OnePlus CM12.1 Build

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

127|root@htc_hiaeuhl:/ # cat /proc/version
Linux version 3.10.84-perf-g48c3e0b (and@AABM) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Fri Jan 22 23:39:28 CST 2016
## Issue:

Nethunter Terminal crashes when using Kali Shell, did try the solutions from https://github.com/offensive-security/kali-nethunter/issues/420, all did work except, busybox installed etc. but the bootkali command still doesn't recognize busybox.

Does the HTC One A9 use other paths than the preset path in the bootkali command, or why does this happen?.

**Comment by jcadduono** [comment]
never flash a build made for another device on your device, and if you see anyone else telling people to do that, kindly tell them they're absolutely wrong in doing so.
if you absolutely must have the nethunter app collection and rootfs on your device, you can use the generic zips from build.nethunter.com/nightly (see the wiki) for your device architecture.

a nethunter kernel must be built for your device in order to use any of the OTG functions including wifi!
kernels are not universal!
