### ISSUE TITLE
HOW TO MANUALLY INSTALL CHROOT IN NETHUNTER AS MY TERMINAL IS CRASHING IT SAY NO BIN/BASH IN DIRECTORY WHEN WRITED BOOT KALI IN TERMINAL

### ISSUE THREAD

**Issue by clavodestiriouso** [offensive-security/kali-nethunter#731]
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

CHROOT:CANT EXECUTEBIN/BASH NO SUCH FILE OR DIRECTORY

## Issue:
HOW TO MANUALLY INSTALL CHROOT IN NETHUNTER AS MY TERMINAL IS CRASHING IT SAY NO BIN/BASH IN DIRECTORY WHEN WRITED BOOT KALI IN TERMINAL WHEN WRITED BOOT KALI IN TERMINAL OUTPUT IS CHROOT:CANT EXECUTEBIN/BASH NO SUCH FILE OR DIRECTORY

**Comment by Zarkopafilis** [comment]
Uninstall chroot, remove all 3 apps; grab a fresh master branch copy of the nethunter repo, locate the 3 apks and install in this order: 1. Terminal 2. VNC 3. Nethunter

It needs to happen in this order because there are Intents that need to be registered for nethunter to not crash at random times.

Then, reinstall chroot. If all of these steps fail (or your installation crashed when booting for the first time- which you may have not noticed btw), you'd have to wipe it clean and retry.

**Comment by clavodestiriouso** [comment]
thnx bro it figured out :)
