### ISSUE TITLE
[suggestion] simple guides

### ISSUE THREAD

**Issue by vay3t** [offensive-security/kali-nethunter#735]
I know that many of those who are here know how to install a kernel with twrp or update android without OTA. But not all keep the subject. My suggestion is in the wiki: add reference links or at best, explanatory steps of how to update a kernel or install nougat when the device does not have official support. (among other things) Will help a lot of newbies just entering the world of android. And at the same time help the community by testing the latest updates without making unnecessary steps

**Comment by mpkosewski** [comment]
Agreed! There are so many "how to's" out there, and I'm still confused on the very basic structure of how it should be done. @_@

**Comment by Zarkopafilis** [comment]
Well, you can't easily install nethunter if you have no clue on how android works and never installed a custom ROM/changed recovery/unlocked bootloader of a device (or even without making some android apps). Hell, it took me 2.5 days to figure out how to make stuff work for the OnePlus One and I ended up doing half of the installation by hand cause first boot hanged. It's tricky, but it worked. It is also common programmer-sense so I suggest you don't start believing everything on the internet. For example, you don't need to install busybox like many people say, it comes bundled with CM , for CM verrsions <= 12.1 , you don't need to flash GApps, they are already there. You don't need to flash superSU before installing nethunter, I could go on....

Just experiment a bit and everything will be fine.

**Comment by mpkosewski** [comment]
Well I know a decent amount about android and I've flashed Android devices hundreds of times(many in a different environment) and my own. It's just that for whatever reason, I just run into 1 issue and I spend a good amount of time trying to research why it's acting that way and how to fix. But one thing can lead to another trying to figure out why one fixed worked partly or why not at all, double checking everything that's needed to be done. Can't say I'm very structured at troubleshooting though at times, just very persistent till I get to a point where I my brain starts losing track of where I started lol 

More-so irritated now because I can't reauthorize my nexus 5 on my pc or kali box to start over and from the looks of it, it had possibly something to do with Google's secure USB debugging feature on them. I didn't read too much into it atm needing a break, so I just left it at that for now. This happened the last time I flashed them and trying to install nethunter. I couldn't reauthorize them till the next day or so.

I had them mostly completed before but couldn't get them to recognize my alfa dongle like my nexus 7 does. None of them though, recognize the network device driver built into them. Today, I learned that possibly the kernel headers weren't flashed right or just needed a new one. So I tried that, didn't work, kernel header didn't change so thought I'd just do one from scratch just to be sure. But then I ran into the issue of not being able to authorize them with my pc or kali box and spent more time trying to see if there was a way around it...... /dead

**Comment by vay3t** [comment]
@mpkosewski Maybe you want to see this #341 
@Zarkopafilis I mean specific things regarding nethunter.

**Comment by mpkosewski** [comment]
You sir, just saved me a world of headaches and heartaches lol

**Comment by mpkosewski** [comment]
It does arouse a few more questions, but pretty much makes sense about my problem with my nexus 5's. Like my nexus 7 pretty much works without error, minus a few small things and my user errors lol

**Comment by vay3t** [comment]
if u have questions with n5 and n7 u can ask me via twitter

**Comment by mpkosewski** [comment]
Oh right on. I would but I don't have anymore social media accounts anymore really,  especially after working for Facebook. Lol

**Comment by phr34k0** [comment]
Please also do add a guide for people having problems with that "Most Supported Phone" Oneplus One. Especially CM12.1 (which hangs and crashes MOST if not all random times) and CM13 (which have that OTG and 100% battery bug. Y-cable issue). Please view - https://github.com/offensive-security/kali-nethunter/issues/732 

idlekernel.com is nomore so users can't grab files from that link. They changed it to https://build.nethunter.com/nightly/

Those files that has been put up on Nethunter site definitely does not work.

**Comment by Zarkopafilis** [comment]
@phr34k0 I failed to install nethunter with CM 13 ( I think kernel needed an update , but it was inside the supported range). CM 12.1 install with updated kernel to 5.0 didn't go smooth either, ended up installing many apps manually. After of 1-2 days of crashes and some tinkering, phone has 3 days of uptime, no weird stutters or whatever.

**Comment by phr34k0** [comment]
@Zarkopafilis Welp, here's what i used, 

- CM13 cm-13.0-20161220-SNAPSHOT-ZNH5YAO3XH-bacon.zip - https://download.cyanogenmod.org/?device=bacon , 

- kernel-nethunter-bacon-marshmallow-20160804.zip from compiled by Phreya - https://www.androidfilehost.com/?w=files&flid=50946 

- update-nethunter-bacon-marshmallow-20160804.zip compiled by Phreya - https://www.androidfilehost.com/?w=files&flid=50946

- Latest TWRP twrp-3.0.2-0-bacon.img - https://dl.twrp.me/bacon/

- latest SuperSU v2.79 SR1 - https://plus.google.com/+Chainfire  extracted everything in nethunter-oneplus1-lollipop-3.0.zip\data\app from nethunter-oneplus1-lollipop-3.0.zip which you can grab from https://www.offensive-security.com/kali-linux-nethunter-download/ ( CM12.1 ) replace the ones on your current phone once you made sure the phone boots up alright without hangups and issues. 

- Deleted chroot from nethunter app

- Update nethunter app from within the app itself

- Downloaded a new chroot from nethunter app

- Reboot phone and see if it works well

Do make sure it is a Clean Install else all past bugs will still linger in the phone.

**Comment by Zarkopafilis** [comment]
@phr34k0 Why is there a need to install update-nethunter-bacon-marshmallow too? Also, thx for the info, but as soon as I'm stable, no need to update...

**Comment by phr34k0** [comment]
@Zarkopafilis Idk i just did it just to make sure it works. One can always skip it. Spent almost a month carrying a buggy CM12.1 phone i can't afford another month having it crashing while at work XD

**Comment by phr34k0** [comment]
@Zarkopafilis oh yeah now i remembered. There was a system level error or something if you used nethunter-oneplus1-lollipop-3.0.zip right before that kernel-nethunter-bacon-marshmallow-20160804.zip and new SuperSU. Hence i had to extract the apps instead and used the update-nethunter-bacon-marshmallow. One can just replace the kernel in nethunter-oneplus1-lollipop-3.0.zip and SuperSU used but i was lazy to go on digging and on an alternate route

**Comment by Zarkopafilis** [comment]
So I did good not bothering and just clean installing cm 12.1 with a
multirom patched kernel (5.0 - only used multirom to update it
automatically). I'm switching to a OP 3T or axon 7 soon (I hope). I'll tell
people how it went too...

**Comment by phr34k0** [comment]
Didn't went ahead as far as multirom as it consumes space but i gave i might have a look at your method one of these days :) Apparently NFC works well over CM12.1 rather than CM13. Might have to wait a while longer till there's a better stable for CM12.1. Might switch to OP 3 too. Love me some 6 GB RAM with 128 storage

**Comment by Zarkopafilis** [comment]
At least when I really needed to make a call and nethunter didn't boot, I
used multirom and booted to a cm13 backup :) cheers

**Comment by vay3t** [comment]
I would appreciate the addition of the steps to install LineageOS in nexus 5

**Comment by Zarkopafilis** [comment]
@vay3t lineageOS is still setting up proper build servers, please be patient, the just started working. I'd suggest to not go full on it, let it be battle tested and stable under normal conditions first. Also, we don't know wether they plan to support a version of android < 7 (for most developer friendly devices at least). 

P.S. The install procedure should be the same one, or at the worse case, a recovery update would be required (if they act stupid and break compatibility , because it's a CM fork/clone after all).

**Comment by vay3t** [comment]
Nethunter image already exists --> https://build.nethunter.com/nethunteros/CM14_1/hammerhead/LOS-hammerhead-14.1-20170102-nethunteros.zip

**Comment by Zarkopafilis** [comment]
I wouldn't recommend it unless you have a spare phone and time to kill tho

**Comment by ThatGuy626** [comment]
Anyone got nethunter and fruitywifi working yet lol its a pain in the ass error after error

Nexus 5 Hammerhead ;)

**Comment by intosec** [comment]
@ThatGuy626 try "systemctl start php7.0-fpm"

**Comment by mpkosewski** [comment]
I've got all my nethunter's working off the stock marshmallow rom's. Working great so far =)

**Comment by akrolla** [comment]
we are all active on twitter.

**Comment by akrolla** [comment]
the wiki is pretty straight forward on how to install the software, where it lacks is instructions on how to use the tools, but thats up to you to learn..... TRY HARDER don't forget, thats OFFSEC's motto

**Comment by phr34k0** [comment]
"Trying harder" is great but not when downloads on the official site comes with hangs and an unstable CM12.1. Someone need to take that down, stash a 5.0 kernel or least rename it to OnePlus One CM 12.1 (Multirom). Lol. Just saying.

**Comment by Zarkopafilis** [comment]
Try harder...

**Comment by phr34k0** [comment]
Yeah that's what we did ;) hahaha :P . Who was this thread starter again? lolol
