### ISSUE TITLE
Mana-nat-simple-bdf

### ISSUE THREAD

**Issue by ozsteyr** [offensive-security/kali-nethunter#775]
### Device:

Op3

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow

### Built from repo (date and build command) or downloaded from website (links):

Latest nightly, 27.02.17

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.18.20-ElementalX-OP3-0.15 (root@nh-buildbox) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #5 SMP PREEMPT Mon Nov 21 17:40:25 CST 2016

## Issue:

Mana-nat-simple-bdf issue, this one I don't know where to begin

dnsmasq: failed to create listening socket for 10.0.0.1: Address already in use
RTNETLINK answers: File exists
MANA - Directed probe request for foreign SSID 'ZTE Blade A462' from 8c:7c:b5:67:cc:42
Traceback (most recent call last):
  File "./bdf_proxy.py", line 819, in <module>
    resourceScript = user_config['Overall']['resourceScriptFile']
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'resourceScriptFile'
Hit enter to kill me.

**Comment by jmingov** [comment]
YO are conected to a network (WIFI) with internal range 10.0.0.0/24, so mana cant run up over the same range, you should be able to edit the config file from the app, and change this lines:

https://github.com/offensive-security/nethunter-utils/blob/master/usr/share/mana-toolkit/run-mana/start-nat-simple-bdf-lollipop.sh#L12

https://github.com/offensive-security/nethunter-utils/blob/master/usr/share/mana-toolkit/run-mana/start-nat-simple-bdf-lollipop.sh#L16

https://github.com/offensive-security/nethunter-utils/blob/master/usr/share/mana-toolkit/run-mana/start-nat-simple-bdf-lollipop.sh#L34

You can use any other private range, like 192.168.0.0 or 172.16.0.0, since 10.0.0.0 is already in use as you can see in this line: 

> dnsmasq: failed to create listening socket for 10.0.0.1: Address already in use

**Comment by ozsteyr** [comment]
Yep, getting there. Still this though.

ee:fb:d9:37:f3
Traceback (most recent call last):
  File "./bdf_proxy.py", line 819, in <module>
    resourceScript = user_config['Overall']['resourceScriptFile']
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'resourceScriptFile'
Hit enter to kill me

**Comment by ozsteyr** [comment]
Yep, getting there. Still this though.

ee:fb:d9:37:f3
Traceback (most recent call last):
  File "./bdf_proxy.py", line 819, in <module>
    resourceScript = user_config['Overall']['resourceScriptFile']
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'resourceScriptFile'
Hit enter to kill me

**Comment by ozsteyr** [comment]
Yep, getting there. Still this though.

ee:fb:d9:37:f3
Traceback (most recent call last):
  File "./bdf_proxy.py", line 819, in <module>
    resourceScript = user_config['Overall']['resourceScriptFile']
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'resourceScriptFile'
Hit enter to kill me
