### ISSUE TITLE
Kali Nethunter probleme

### ISSUE THREAD

**Issue by kerbecs** [offensive-security/kali-nethunter#793]
Hello,sorry but I do not know English,but I have a problem,
I write in Monitor Mode "wifite",but something strange occurs

Wlan1:ERROR while getting interface flags: No such device

.;' ;, .;' ,;';, ;, WiFite v2 (r85) .;' ,;' ,;';, ;,;,
:: :: : ( ) : :: :: automated wireless auditor
':. ':. ':. /\ ,:' ,:' ,:'
':. ':. /\ ,:' ,:' designed for Linux
':. /___\ ,:'
/ \

[!] the program cowpatty is not required, but is recommended

[+] scanning for wireless devices...
[+] available wireless devices:

   1. P2p0       ????????       unable to detect for sdio 0x02d0:0x4334
   2. wlan0      ????????       unable to detect for sdio 0x02d0:0x4334
[+]select number of device to put into monitor mode (1-2):
1
[+]enabling monitor mode on p2p0... done
[+]available wirelesdevices:
   1. p2p0             ????????        unable to detect for sdio 0x02d0:0x434  
   2. wlan0              ????????        unable to detect for sdio 0x02d0:0x434 
    [+] select number of device to put into monitor mode (1-2):

please help me :((

**Comment by akrolla** [comment]
Bfore running wifite did you run

Source monstart-nh
And then run wifite

And once finished run
Source monstop-nh

**Comment by kerbecs** [comment]
Appear: 
wlan1: ERROR while getting interface flags: No such device  root@kali:/# source                                        
root@kali:/# source monstart-nh
bash: monstart-nh: No such file or directory
root@kali:/#

**Comment by AutinDroid** [comment]
@kebercs Are you using the official kali-nethunter? That thing is deprecated, so get for build.nethunter.com/nightly. Flash the hammerheadmon-nougat package and the armhf generic kalifs. Then source monstart-nh. You need a nougat ROM for this to work.

**Comment by kerbecs** [comment]
build.nethunter.com/nightly  must be installed width recovery?T his is Kali NetHunter program  or something else ? Sorry , but I  only just started to work with her and not too experienced .

**Comment by AutinDroid** [comment]
First install nougat ROM and then Flash https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-armhf-kalifs-minimal-rolling-3.15.4-20170211-0304.zip and kernel-nethunter-hammerheadmon-marshmallow-3.15.4-20170211-0304.zip. yes, this is Kali nethunter.

**Comment by AutinDroid** [comment]
Flash via twrp

**Comment by kerbecs** [comment]
program was installed,but a problem,I open monitor mode from Kali NetHuntet,and opens terminals android,but then closes and write Window No Title.I managed to see an error:
eco -ne "\033]0:Wlan1 Monitor UP\004 && clear:sudo ifconfig wlan1 &&sudi iwconfig wlan1 mode monitor &&sudo ifconfig wlan1 && echo "wlan1 Monitor mode enabled" && sleep 3 &&exit
I use cyanogen mod 12.1,Busybox and root.
Please help me

**Comment by AutinDroid** [comment]
@kerbecs you are probably using the deprecated official installer. Please follow my instructions. You are supposed to have nougat, not cm12.1 for best results

**Comment by kerbecs** [comment]
even with android nougat the error occurs :(

**Comment by AutinDroid** [comment]
@kerbecs Why not use airmon? What wifi card are you using.

**Comment by kerbecs** [comment]
what do you mean wifi card?I forgot to say,i have samsung galaxy s3 gt i-9300

**Comment by velazguez** [comment]
Nexus 10 Nethunter Help #803 @AutinDroid

**Comment by AutinDroid** [comment]
Oh so sorry @kerbecs assumed ur device was hammerhead. Lemme find proper kernel 4 u. The one I sent is for hammerhead

**Comment by kerbecs** [comment]
where can I take ?

**Comment by kerbecs** [comment]
But there is a portable version?

**Comment by kerbecs** [comment]
up please

**Comment by kerbecs** [comment]
Hmmm,this command works without a wifi adapter?

**Comment by kerbecs** [comment]
up please

**Comment by kerbecs** [comment]
up

**Comment by AutinDroid** [comment]
@kerbecs So sorry for not responding for half a month. I've been super busy, and I kinda forgot about nethunter. I don't think s3 is supported, but I am going to be porting many devices (including s3) this weekend

**Comment by kerbecs** [comment]
I actually found a portable version,but pretty bad.
command wifite It works only with a WiFiadapter?

**Comment by kerbecs** [comment]
up

**Comment by kerbecs** [comment]
upp

**Comment by akrolla** [comment]
It used to we incorporated nexmon into the platform

before launching wifite run the command
 source monstart-nh
Then start wifite
make sure u are disconnected from wifi before do not want to damage the
radio. And than u should see wlan0 as an option
To stop
source monstop-nh
U may have to run the command twice I get an error because the lib hasn't
been updated it still worka properly on my device I just have to run the
command twice to stop it after you stop you can then reconnwct back to wifi
normally, to prevent damage to the radio make sure to get off of your wifi
AP. Leave wifi on though.

**Comment by dciphr** [comment]
Does this work when using the generic ROM in the nightly builds (instead of the CM14.1)? I actually generated my own build from the GitHub repository for angler (flashed stock 7.1.2, flashed twrp, ran build.py and installed generated generic ROM and angler kernel via twrp) but appears the nexmon patch isn't included. How would I go about building nexmon into the ROM generated by build.py ? Sorry if this is the wrong forum to ask this in, but I haven't had much luck.

I also tried manually compiling the nexmon patch using instructions at https://github.com/seemoo-lab/nexmon however monstart-nh doesn't exist and it appears I can't manually execute nexutil -m2 from the nethunter kali terminal only the adb shell.

Any direction would be much appreciated.

Thanks!

**Comment by hussnain27** [comment]
Is nethunter kermel compactible wit all devices (I have huawei media pad)

**Comment by oliverk71** [comment]
I have the same error on my Nexus 10. And yes, I used the official build (Lollipop), too. After reading the comments above I downloaded the nightly build for Lollipop, but the install failed. I did not try Nougat yet. Anyway, I could have started from the newest LineageOS, it would not have been more trouble, I guess. :D

btw: I have another device (Samsung GT-i8190) and installed Nethunter App, Chroot, SuperSu etc on top of LineageOS 14 (Android 7.1.1), but there I can't use terminal commands like airmon-ng or even apt-get. Had this on the Nexus, too, but was able to find a solution for that, which unfortunately did not work on the GT-i8190: su 0 kalilinux_bootlogin.

Well, I would like to know, if there is any official or nightly build, which is known to work better on the Nexus 10 and maybe the GT-i8190 too.

**Comment by la-maka** [comment]
hi. The problem remains topical. Device - Nexus 5 marshmallow, I wose testing 2 external wifi card china`s mediatek device and Alfa awus036nh. I wose trying install NH two ways, without TWRP and whit it. Nothing changes.  lsusb and dmesg see devices, but there is no network interface. I thought on dmg from the PC, both devices use the rt2800usb driver. The first thought was to find the driver for the corresponding architecture and put it next to the others. But I do not know much android and it did not help. The next idea. I bought the phone not new and maybe the basic firmware before the update was Lollipop, because I chose the wrong archive with the NH. This is unlikely, but I think I should try it.
It's not cool, when the officially supported device is working so badly, I'm upset.
