### ISSUE TITLE
Everything workinf perfectly! But maybe to help clear up some confusion...

### ISSUE THREAD

**Issue by Jinovas** [offensive-security/kali-nethunter#810]
**Device:**

Nexus 7 (2013)

**OS version (KitKat/Lollipop/Marshmallow/Nougat):**

Nexus 7 = Marshmallow 6.0.1 MOB30X

**Built from repo (date and build command) or downloaded from website (links):**

Using only nightly builds:  
nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170211-0304.zip ~~~> Flashed first
kernel-nethunter-flo-marshmallow-3.15.4-20170211-0304.zip ~~~> Flashed second

**Output of cat /proc/version in adb shell or NetHunter Terminal:**

Linux kali 3.4.0-gae95f7e-dirty #1 SMP PREEMPT Fri Jul 29 23:09:11 CDT 2016 armv7l GNU/Linux it in a bit)

**Issue:**

Wasn't sure where to post this so figured put it in the heart of where people are coming to looking for help. So far after wiping and reflashing everything, I've gotten everything working perfectly WITHOUT any errors/issues. In fact, everything runs super smooth and solid where as before, I was always dealing with buggy/glitchy kali terminal issues, wifi adapter issues, unable to update kernel even after flashing it with TWRP, etc. I'm even seeing a few things I never saw before like the Wardriving section of the nethunter app actually show a page with kismet! Here I was trying to use kismet via terminal still lol I Haven't fully tested everything with any of my Alfa wifi adapters yet, but I will once it's done updating and verify if they work. Adapter's I have are: AWUS036NH, AWUS036NEH, and AWUS03NHA.

I've run into a lot of the same issues that have been plaguing the issues board here and I think a big part of it is possibly due to confusion on how to properly flash everything in the right steps as well as where to download nethunter from. The #1 thing I did differently this time around was not using any build from the Kali NetHunter official website. I specifically ONLY used the generic full-chroot build as well as the separate kernel specified for my device from the nightly builds link. In short, once I did that, I ran the whole setup without any problems which has never happened before lol

I was thinking of creating a tutorial or walkthrough to help clear up any specific questions anyone might have that may not be particularly addressed, but figured I'd post something here first and get other's thought's/opinions.

One thing's for sure, my Nexus 5 is next to get reflashed and setup the same way lol

**Comment by mpkosewski** [comment]
I knew my luck would run out >_< awus036neh is not being seen under iwconfig. Lsusb sees it, airmon-ng sees it(still with "??????" for the driver though). 

And I still not sure what this "dummy0" device is. It stays when I unplug the adapter. 

Here a few screens if it helps:

**Comment by VFMA83** [comment]
YES, please post your tutorial. I have installed - uninstalled 20 times with no luck.  I rooted, unlocked the bootloader and followed all the steps but the apt will not update and the external wifi will not work (????)  I have a Nexus 10 running 5.1.1. I have watch tons of install video's and followed many post with no luck.  Thank you!

**Comment by mpkosewski** [comment]
Ok I can put one together a bit later today. I am curious though, does your wifi adapters led lights turn on? What does lsusb, iwconfig and airmon-ng all say? Curious if it's like mine. 

Also, if airmon-ng shows a wlan1 device, use airmon-ng to put it in monitor mode and try airodump-ng. Cuz i think mine still technically worked that way. I'll have to try later after I take care of an appointment @_@

**Comment by VFMA83** [comment]
Thank you for the response.  

Here is what I have:

Android Version: 5.1.1
 
Build number LMY47V
 
Kernal Version:
3.4.67-00092-g7b02438
root@kali#1

Device: Kali Nethunter on a Nexus 10

OS version (KitKat/Lollipop/Marshmallow/Nougat): Android 5.1.1

Built from repo (date and build command) or downloaded from website (links): LMY47V
 
I am using an Alfa Networks AWUS036NEH wireless card with a new OTG cable.  (The internal wireless works but the external.) The blue light goes on.
 
When I go to the terminal and do a iwconfig it see wlan0 with an IP, etc,  but the Wlan1  says  “No wireless extension found?” (?????)  I am assuming it is a driver issues but I bought the card that was supported out of the box.

**Comment by mpkosewski** [comment]
It's fully supported on a real Linux machine, not Android. Well one thing is for sure, we got sane issue it looks like! 

Last night I've dived into the system/device/driver/anything I could find with configuration files and couldn't find much( although my coding is still limited). We're gunna need someone with more knowledge in the actual development of Linux and Android softwares. 

I posted an idea I had though I don't remember where I got it from; but from the dmesg logs, nethunter (or maybe Android) is having an issue or conflict with powering the adapters and putting the USB connection in low power mode. Which makes sense that we see the led and that nethunter can barely see it. Sounds like they're not getting enough power. If that makes sense? 

Still got research to do on that possibility.

**Comment by mpkosewski** [comment]
Ok think I found more clues that it might be a kernel module problem since I'm having some weird issues trying to see them and using the kmod commands. Missing folders/or doesn't show any modules loaded etc. 
![screenshot_20170227-150434](https://cloud.githubusercontent.com/assets/13728103/23384814/40eee16c-fd01-11e6-8fbd-fa7288e69a7a.png)

**Comment by mpkosewski** [comment]
Sry taking so long for the guide, got caught up in fucking with the wifi issue. My brain is burnt suffering the same issue @_@

Looks to be a driver or module issue. Either missing or misplaced or something

**Comment by kimocoder** [comment]
Visit #NetHunter @ freenode for more help may i suggest, if you're still got troubles :)

**Comment by mpkosewski** [comment]
Will do!

**Comment by mpkosewski** [comment]
Also, for some success, I randomly found an old edimax wifi adapter, tried it and I got it to work! I had to set the TX power, but iwconfig sees it and seems to be working @_@

**Comment by king0demons** [comment]
Well, since you haven't updated I figured id share my results:
Nexus 7 2013 wifi (flo)
Stock 6.0.1 MOB30X
Generic full rolling 3.15.4-20170211-0304
Nethunter flo marshmellow 3.15.4-20170211-0304 kernal
otg cable not y cable
TL-WN722N Dongle
after having run apt-get upgrade, update, dist-upgrade
![screenshot_20170325-231139 1](https://cloud.githubusercontent.com/assets/26682592/24328208/7e8f8cfa-11b1-11e7-97e3-bb0a08a988ae.png)
![screenshot_20170325-231127 1](https://cloud.githubusercontent.com/assets/26682592/24328209/81a9420a-11b1-11e7-9b79-a789bfaf2aae.png)

**Comment by pddevins** [comment]
*** Device:
Asus Nexus 7 gen 2 (2013)
Edimax (RTL8188CUS) Wifi Dongle

*** OS version (KitKat/Lollipop/Marshmallow/Nougat):
Stock from Nexus site
Android Version: 6.0.1 Marshmallow
Kernel Version: 3.4.0-gae95f7e-dirty

*** Built from repo (date and build command) or downloaded from website (links):
Built from official repo on 2-20-2018 for -flo -marshmallow

*** Output of cat /proc/version in adb shell or NetHunter Terminal:
Linux version 3.4.0-gae95f7e-dirty (root@nhbuild-box) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Fri Jul 29 23:09:11 CDT 2016

*** Output of lsusb:
Bus 001 Device 002: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

===

This device appeared on `wlan1`, but any attempt to put it into monitor mode from there was unsuccessful, however I was able to successfully get this adapter to appear with `iw` and look at it's capabilities (which listed monitor mode):

I then used the following set of commands to get a monitor-mode device
```
iw phy phy3 interface add mon0 type monitor
ifconfig mon0 up
iw dev mon0 set freq 2437
```

verified that it can capture with `tcpdump`, however it shows as `no wireless extensions` on `iwconfig mon0`, and is `unspec` (as opposed to `inet`) in ifconfig.

I'm curious to know more details about how @Jinovas got the Edimax rt8192 device to show up in `iwconfig`, because so far I get `no wireless extensions` for both the `wlan1` that appears automatically, and for the `mon0` device that I create with `iw`.

**Comment by bozwald** [comment]
Try airmon-ng start wlan0 this will bring it into monitor mode if wifite
won't

**Comment by pddevins** [comment]
Just got my AWUS036NEH and plugged it in with the same old ???????? driver, BUT i don't have to use `iw` to configure the device. `iwconfig` and `ifconfig` show the device as wlan1. I can put the device into monitor mode with airmon,but wifite wont do it and iwconfig wlan1 mode monitor reports that its unsupported. Goong to try reflashing with generic and then flashing the flo kernel ontop of that as @Jinovas did and see what happens.

**Comment by bozwald** [comment]
You can enable it in airmon-ng and then use wifite

**Comment by pddevins** [comment]
@bozwald, for sure. Thanks. I reflashed with 3.15 as @Jinovus had mentioned and the adapter actually showed up with airmon. Still all ? For driver, but the adapter info populated correctly. I was able to successfully throw it into monitor mode with airmon and then started Wifite with —mon-iface set to the monitored device name. I couldn’t get it to successfully engage a handshake, but it was picking up APs in the area. Reflashing tonight with 2017.11-18-1618 dir generic and foo kernel to see if it gets me any further down the rabbit hole. 

On forst boot, with the nexus 7, how long should the google logo be up for? I don’t want to interrupt any initialization that’s occurring, but I also don’t want it to just sit there in a boot loop. On past flashes, I’ve let it sit for 2-ish hours then I’ll restart, Kali boot animation flashes for a second then it restarts and sits on the google logo again, then I restart the tablet again and it fully boots. It sees chroot, and seems to work fine, I’m just curious if I’ve been restarting it during an initialization that sets up the drivers or something and that’s why all my drivers (even internal Wi-Fi) are ??s in airmon. (Obviously I haven’t gotten into messing with kernels and configurations yet to know what is happening when)

**Comment by pddevins** [comment]
## Update: Nexus 7 (2013) Stock 6.0.1 w/ Nethunter 2017.11-18-1618
Flashed `generic` and `flo` kernel and everything is working pretty much perfectly. Had to modify the custom commands for **Wlan1 Monitor Mode** and **Wifite** so that the former does `airmon-ng start wlan1` and the latter includes the flag `--mon-iface wlan1mon` (the consistent name that airmon puts my wlan1 into). The latest build, for whatever reason, worked with the external Alfa card. It's the same kernel, so who knows what bumped all the tumblers into place. ¯\_(ツ)_/¯ 

Thanks for the reassurances @bozwald, and thanks for the push in the right direction @Jinovas.
