### ISSUE TITLE
Note 4 N910f nethunter inst. Prob 

### ISSUE THREAD

**Issue by mimote** [offensive-security/kali-nethunter#811]
## Issue:
Hi
i got some trouble to install nethunter on the the Device 

Which kernel can i use and where to find? 
The next Problem Which Version of nethunter is the correct one? 

Can somebody help me,please

**Comment by zonkeynet** [comment]
From stock ROM android marshmallow 6.0.1 
flash this kernel - 
AEL kernel v10.8 https://androidfilehost.com/?fid=457095661767103182
Than again flash the last nethunter zip kalif for marshmallow 
example:
https://build.nethunter.com/release/marshmallow/nethunter-bullhead-marshmallow-kalifs-full-3.20-20170717-1810.zip
wipe cache etc...Reboot
Open Nethunter app and install the chroot!
I Hope this help you  :)
Sorry for my poor english.
N.B. If you have allready root your device remove all supersu file from the zip before flash.
And a full backup can save your device in case of something wrong.

**Comment by jcadduono** [comment]
please don't flash zips for other devices on different devices, use a generic arch build from nightlies

https://build.nethunter.com/nightly/2017.10-20171013-0449/nethunter-generic-armhf-kalifs-full-rolling-2017.10-20171013-0449.zip

flash **after** whatever custom kernel you wanted to use

**Comment by jonniex7** [comment]
any new kernel suport for ported roms?

**Comment by Rinilyn** [comment]
tested it on samsung galaxy note 4 N910C. Everything looks fine. Except it doesn't detect exterial wifi cards. Only Wlan0 is shown which is not what we need. using a custom kernel( 3.10.9-talexop-1.5_noDMV+)
this kernel was important to me because it changes SE to permissive. i tried flashing what @zonkeynet Kernel provided even thought im not stock ROM. and then i reflashed the nightly build from @jcadduono post. I'll appreciate any feedback or tip if im messing up, thanks in advance
