### ISSUE TITLE
Camera problem with nethunter

### ISSUE THREAD

**Issue by xTheCrow** [offensive-security/kali-nethunter#818]
### Device:
Nexus 5x

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

Nougat

### Built from repo (date and build command) or downloaded from website (links):

python build.py -d bullhead --nougat -fs full

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

root@kali:/# cat /proc/version
Linux version 3.10.73kali-gddc7121 (root@nhbuild-box) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #2 SMP PREEMPT Wed Aug 24 20:47:30 CDT 2016
root@kali:/#

## Issue:

the camera has a problem, even with another camera app
![430401745_33217_4228530174226919010](https://cloud.githubusercontent.com/assets/26142117/23556208/135a4452-002c-11e7-8474-e6fd724382aa.jpg)
![426121907_231249_12922010384152366185](https://cloud.githubusercontent.com/assets/26142117/23556209/1506c1c2-002c-11e7-8b1c-f8914a211e1f.jpg)

**Comment by Nathitshe** [comment]
Same for me !!!!!!! And the video mode send me an error : _"There was a problem with the media recorder"_ and does not record what I took.

And the picture mode save a **very dark photo** too :

![img_20170303_183441](https://cloud.githubusercontent.com/assets/13369175/23561827/3c8dee78-0040-11e7-9c25-3d73ca329a2e.jpg)

**Comment by Nathitshe** [comment]
So I can't use the camera...

**Comment by stesesia** [comment]
Exact same phone and build and same problem, as soon as I install nethunter the camera turns very dark and I cannot use it

**Comment by xTheCrow** [comment]
up

**Comment by elitedevx** [comment]
I'm having the exact same issue here too.
Please let me know what information I can provide to help locate the problem.

**Comment by Laser89** [comment]
I got temporary fix for the issues of external wifi cards not being connected or recognized & and it will fix also the camera (because mine is not working or not connected error message showing)

Before anything else you should clean install compatible .img and or nethunter .zip on your device.

Before installing nethunter install flashify and backup current kernel, you can save on your google drive, dropbox or use otg thumbdrive to save.
Now Install nethunter.
If you want to use your external wifi don't flashed the kernel which I told you to backup. (As is)
If you want to use your camera just flash the kernel which I told you to backup ;)
Hope it works on you.. coz mine is ;)

NOTE: this is just temporary fix.. so you can get going whatever you want to do ;)
