### ISSUE TITLE
WLAN1 not working

### ISSUE THREAD

**Issue by hightechstl** [offensive-security/kali-nethunter#835]
### Built from repo (date and build command) or downloaded from website (links):
https://forum.xda-developers.com/galaxy-s6/development/kali-nethunter-s6-s6edge-stock-rom-t3559710

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
root@kali:~# cat /proc/version
Linux version 3.10.101_Stock_Modified_Kernel_ (jovy23@ubuntu) (gcc version 5.3.1 20160401 (optimized) (UBERTC-5.3.x) ) #1 SMP PREEMPT Sun May 22 07:04:19 EDT 2016

## Issue:
Root@kali:~# ifconfig wlan1 up
wlan1: ERROR while getting interface flags: No such device

lan1: ERROR while getting interface flags: No such device

root@kali:~# usb-devices

T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 1
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=03.10
S:  Manufacturer=Linux 3.10.101_Stock_Modified_Kernel_ xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=xhci-hcd.2.auto
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=148f ProdID=3070 Rev=01.01
S:  Manufacturer=Ralink
S:  Product=802.11 n WLAN
S:  SerialNumber=1.0
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=450mA
I:  If#= 0 Alt= 0 #EPs= 7 Cls=ff(vend.) Sub=ff Prot=ff Driver=(none)
T:  Bus=02 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=5000 MxCh= 1
D:  Ver= 3.00 Cls=09(hub  ) Sub=00 Prot=03 MxPS= 9 #Cfgs=  1
P:  Vendor=1d6b ProdID=0003 Rev=03.10
S:  Manufacturer=Linux 3.10.101_Stock_Modified_Kernel_ xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=xhci-hcd.2.auto
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

root@kali:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

External adapter is AWUS036NEH and works fine on my nexus 7 and nexus 5 without aby extra configuration. Just can't get it working on here

**Comment by hightechstl** [comment]
It may be important to note that my OTG cable is not a Y cable.

**Comment by hightechstl** [comment]
I've tried that.

root@kali:~# ifconfig wlan1
wlan1: error fetching interface information: Device not found


root@kali:~# ifconfig wlan1 up
wlan1: ERROR while getting interface flags: No such device

**Comment by hightechstl** [comment]
Anyone have any comment on this?

I have the exact same issue on my NVIDIA Shield tablet

**Comment by ll3N1GmAll** [comment]
What was the fix for this?

**Comment by 0E800** [comment]
Maybe the interface is called something other than wlan1.

Try running airmon-ng, and ifconfig and see what interfaces show up.

What is the external WiFi device model?
If its a tplink what version is it?

**Comment by ll3N1GmAll** [comment]
I have no other wlan interfaces of any number. I have tried the tp-link tl-wn722n & the alfa NIC sold at the hakshop (likely awus036nh or awus036nha).

**Comment by 0E800** [comment]
I have had this happen before :

Turned on device while the ext WiFi is attached.
Device uses external WiFi as wlan0.
Devices built in WiFi does not show.

Try putting wlan0 in monitor mode if you see the green light on.

Another thing that can be happening is the device is sending power but not
data. Or there is just enough to make the led turn on.

With device on, unplug ext WiFi, then plug it back in. Next open nh'term
and type dmesg.

Look for the output related to your ext USB WiFi

**Comment by ll3N1GmAll** [comment]
I tried to use monitor mode and other tools with wlan0; but they reported that the wlan0 was my internal NIC to the phone. As such, the tool did not operate properly. Thanks for your responses, I will try what you have suggested and report back (i've gone for broke and am in the middle of ripping everything out and reinstalling nethunter again out of desperation).

**Comment by 0E800** [comment]
I wouldn't be surprised if it worked after a complete wipe and reinstall.

Are you using stock ROM?

**Comment by ll3N1GmAll** [comment]
I'm not doing a complete factory reset and reinstall. Just trying to remove all nethunter components and reinstalling nethunter. Unfortunately, I have done this a couple times in order to fix the failing NH terminal issue to no avail. I am using the stock oxygen OS on a oneplus.

**Comment by ll3N1GmAll** [comment]
Still no wlan NIC recognition and still no NH terminal functionality...

**Comment by 0E800** [comment]
I'm not convinced that will fix any underlying issue that would be fixed by
a complete wipe.

Especially with regards to having root modifications already made.

All my devices are for dev use as it became time consuming having to go out
of the way to preserve data only to find that 8/10 times a wipe is required.

You can't conclude anything until all possible options have been explored.

**Comment by 0E800** [comment]
If you are unable to run nh.term then how are you able to run airmon-ng?

**Comment by ll3N1GmAll** [comment]
i open an android terminal and type 'su' then 'bootkali'. This gets me into the chroot so i can use kali; but everything from the nethunter app is broken and useless.

**Comment by ll3N1GmAll** [comment]
If a full wipe of a NH device is required 8/10 times a NH issue comes about, then nethunter is completely useless for anything other than something to mess around with in your spare time. I've had better stability and usefulness out of prebuilt kali/debian/ubuntu.img files with corresponding boot scripts. Forgive me if I misunderstood; but is that what you are saying? Are the majority of NH issues only able to be resolved by a wipe?

**Comment by 0E800** [comment]
Its a red flag that the nhterm is not running.

There is a link somewhere around here for the most current version of
nhterm and nh.apk

I'm running errands now, if you don't find by then I'll reply back with it.

**Comment by ll3N1GmAll** [comment]
I have the link. I have tried all published fixes for the nhterm issue including installing the newest version and installing busybox to a specific location, etc. Thanks for your time.

**Comment by ll3N1GmAll** [comment]
After a fresh install of NH only, I needed to open nhterm by itslef to get the SU permission prompt. After getting that and accepting it, the nh term now appears to be working properly. Still not sure about the USB NIC though. I'll try your suggestions and report back. Thanks again!

**Comment by 0E800** [comment]
Just wanted to clarify that the developers that spent their time for r&d ,
adjusting releases to include newer functions and work with a spectrum of
devices just for you to get frustrated with because of how you judge
something provided for free based on expectations of commercial products
you purchased prior.

To expect things to be tailored to your own expectations will only invite
frustration.
He who expects nothing wont ever set himself up to be disappointed.

This project that binkybear started that got the attention of the Kali devs
and bolstered development to make it what it is today is for information
security enthusiasts and professional pentesters , who already know what
they are doing and dedicate a device specifically to be used during a
penetration test or for auditing network security.

Nobody gonna help you with that mentality of entitlement .

Good luck breh

**Comment by ll3N1GmAll** [comment]
I'm not sure what you mean by: **you to get frustrated with because of how you judge something provided for free based on expectations of commercial products you purchased prior.**
I'm not comparing this to any commercial product. This is an issue that is ultimately caused by the NH terminal not prompting for SU permissions when launched by the nethunter app unless the user knows to manually attempt to open the NH terminal app so the SU prompt can be received and accepted. The internet contains numerous reports of this issue causing users problems with no actual identification of the issue causing this behavior. I already have an issue submitted where I am quite politely detailing the issue with specifics and asking for assistance in considering this for rectification. My frustration is due to my efforts in porting my newly released tool to nethunter with these issues. These persistent issues and their lack of useful/available solutions are quite frustrating. I fully admit that. I was very thankful to you for your repsonses and I have taken responsibility for the issue I have correctly identified by sharing with the community and asking that it be addressed by the development team. I am also working to make a tool for the community that is available on as many platforms as possible...this I am doing on my own for free as well. Therefore, your comment "Nobody gonna help you with that mentality of entitlement ." is inappropriate and completely out of line. However, I thank you again for your time and for your assistance earlier. Have a pleasant evening.
