### ISSUE TITLE
No sound, terminal crash

### ISSUE THREAD

**Issue by MbrooGit** [offensive-security/kali-nethunter#848]
### Device:
Nexus 6
### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Nougat 7.1.1
### Built from repo (date and build command) or downloaded from website (links):
https://build.nethunter.com/nightly/3.15.4-20170211-0304/nethunter-generic-armhf-kalifs-full-rolling-3.15.4-20170211-0304.zip
https://build.nethunter.com/nightly/3.15.4-20170211-0304/kernel-nethunter-shamu-nougat-3.15.4-20170211-0304.zip
### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.10.40-g90f4f12 (root@nh-buildbox) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Jan 25 18:18:56 CST 2017
## Issue:
1.Terminal is crashing
2.No sound after kernel update

**Comment by MbrooGit** [comment]
Terminal crash resolved by installing apk of term manually from archive, sound issue resolved by flashing elementalx kernel, but usb keyboard emulation won't work.

**Comment by simonpunk** [comment]
seems developers havent build the latest source for two months already, so I have built one for my nexus 6, but its too large to upload for me, or I just upload the zImage file so that you can then follow the guideline here https://github.com/offensive-security/kali-nethunter/tree/master/nethunter-installer to compile a installer zip for yourself, I will try to upload it tonight if you dont mind waiting.

**Comment by simonpunk** [comment]
also, for any crashes when opening a app, you can download a pure terminal app, and then type the following in the terminal

> su
setenforce 0

it should be good to go. you can do it everytime you boot up your phone.

**Comment by simonpunk** [comment]
[nethunter kernel for shamu 7.1.1](https://drive.google.com/file/d/0B-cBdArdvHDxOVcxWmxic2tIeE0/view?usp=drivesdk)

**Comment by MbrooGit** [comment]
This kernel wont work too

**Comment by simonpunk** [comment]
are you sure your rom is not cm and from the latest offical update? you can check here. https://source.android.com/source/build-numbers#source-code-tags-and-builds
it must be N6F26Y, other roms are unlikely going to work. you must update your rom not just kernel itself, or you can grap the latest boot.img, then flash my zip again.

**Comment by Fuse8499** [comment]
Simon, I'm using the latest version of crDroid (build is N2G47E). Just wanna say your rom kernel works great. My sound works and I'm able to put my otg network adapter into monitor. This has been a 2 month issue for me and you just fixed it. Thanks so much. You rock!

**Comment by Fuse8499** [comment]
I'm on Android 7.1.2 so I didn't expect it to work because I wasn't on the build you suggested but I was pleasantly surprised when it did!

**Comment by MbrooGit** [comment]
Ok, your kernel can give a sound, but if i'll open 'usb keyboard' from pelya, i'll see that app need custom kernel

**Comment by Fuse8499** [comment]
I haven't tested it because I don't really use the USB Keyboard app but been one nightmare after another with Nethunter ever since Google updated to Android N. On half of the roms my USB network adapter isn't even recognized even with the Nethunter kernel installed. So far this is the best kernel I've come across.

**Comment by simonpunk** [comment]
sorry guys , I forgot to mention about the hid function, because I set it to not always enabled, thats why you can not use hid attack before you enable the hid function, to do that, open the terminal in androidsu(not kali), then type: 

> setprop

 sys.usb.config hid

then try again, it should be good to go, the reason why i did that is because I dont want to always enable the hid function just for the flexibility of usb attack. If you dont like it I can compile one again once I get times.

**Comment by MbrooGit** [comment]
Compile if you want help our humanity. But i think its enough. Thank you so much. Closing issue.
