### ISSUE TITLE
Monitor mode on internal on Nexus 7 2012 (3G)

### ISSUE THREAD

**Issue by jeffhammett** [offensive-security/kali-nethunter#85]
I've seen a few posts on the forums and elsewhere stating that the internet wifi could do monitor mode on the Nexus 7 2012. Does anything special need to be done to enable this?

I have NetHunter running ok, and I can put the card into monitor mode manually with airmon-ng, but airodump-ng with the newly created mon0 doesn't find anything. 

I've also tried wifite (both from the Kali Launcher and from a Kali shell) and both allow me to select wlan0, but then the interface selection menu just loops asking me to pick an interface again.

Any ideas on how I can get it work as others have reported?

**Comment by Drugoy** [comment]
A few years have passed - is bcmon's approach still not implemented in nethunter?

**Comment by binkybear** [comment]
TBH there is probably an easier alternative to bcmon using nexmon patch.  However, N7 2012 is aging and there are space issues (in system) and kernel issues (too old).  I'm not going to spend time on it, I would probably rather work on getting the Nexus 5 which already has a kernel that supports monitor mode (with some issues in compatibility).

**Comment by akrolla** [comment]
i did it with the bcm0n apk works perfect with my grouper with tilapia rom and kernel.

**Comment by akrolla** [comment]
and theres a reaver apk alspo that wprks withthe bcm0n apk

**Comment by Drugoy** [comment]
@akrolla could you, please, give more details?
What ROM (link to it, please, if possible)?
What kernel (link to it, please, if possible)?
What versions of bcmon and reaver (link to them, please, if possible)?
Did you do anything else (like changing start/stop scripts in bcmon/reaver)?
Because when I tried (tested on grouper with grouper ROM) - everything failed to work even after following advice to edit start/stop scripts (that was required because reaver looks for them by the wrong paths or something and it logged errors about missing scripts).

**Comment by akrolla** [comment]
My grouper has a tilapia ROM, using pwn pad I think that is why it was
working but reaver never really worked  well...  But all the scripts that
came with the bcmon apk worked as expected I just wish they had  aireplay
...
