### ISSUE TITLE
Nethunter for LineageOS 14.1 (Xperia Z2)

### ISSUE THREAD

**Issue by albertse2** [offensive-security/kali-nethunter#869]
## Issue: What installer should I use on Sony Xperia Z2 D6503 running Lineage OS 14.1?
https://forum.xda-developers.com/xperia-z2/orig-development/rom-lineageos-14-1-sirius-t3577518

Thanks

**Comment by albertse2** [comment]
any can guide me?
please
i need this for my studies =(

**Comment by 3xpl01ts** [comment]
There is no custom kernel for this device. You can modify you kernel by following this [guide](https://build.nethunter.com/nightly/). You can also flash a generic zip from [here](https://build.nethunter.com/nightly/) or build one yourself, but some of the features like the hid attacks won't work, because they need a customized kernel.
