### ISSUE TITLE
NetHunter apps don't send commands to Kali terminal

### ISSUE THREAD

**Issue by eliasps** [offensive-security/kali-nethunter#912]
### Root: MagiskSU

Hello,

I have an issue getting commands into the Kali chroot. When I select for instance "Add metapackages" from the NetHunter app, it launches the NetHunter terminal but the command for the addition of metapackages is being executed in an androidsu shell instead of the Kali. When on that androidsu shell, I type "exit", then it leaves that session and enters the Kali chroot. 

Same goes for the NetHunter terminal, when launched and prompted to select the session (Kali, androidsu or Android), selecting "Kali" will enter an androidsu terminal instead. Typing "bootkali" boots the Kali chroot but doesn't automatically switch into it.

Any ideas?

Thank you in advance,
Elias

**Comment by eliasps** [comment]
Same goes for the NetHunter terminal, when launched and prompted to select the session (Kali, androidsu or Android), selecting "Kali" will enter an androidsu terminal instead. Typing "bootkali" boots the Kali chroot but doesn't automatically switch into it.

**Comment by kimocoder** [comment]
this issue seems related to #900 

I reproduced the problem on Android 7.0.1,  but all works fine here..
What you got in common is you both are running 7.1.2 and experience this.. But it may also be device/kernel/install related but 2 reports from 7.1.2 at the moment may point us in a direction

**Comment by kimocoder** [comment]
one more thing i noticed, the [NetHunter Wiki - Device Support](https://github.com/offensive-security/kali-nethunter/wiki) says "angler" (Nexus 6p) is supported from Android 6.0.1 to 7.1.1.

**Comment by eliasps** [comment]
@kimocoder I had the exact same setup on my phone with the only difference being the OS version (7.1.1 then). I only have this issue on 7.1.2. On 7.1.1 everything worked as expected. So I guess looking into that is a start

**Comment by FallenArchangel** [comment]
I've been having this issue for a while now, haven't found any solution.  I'm on 6.0.1. Samsung Galaxy S7.
Nethunter isn't supported on Nougat for my device, so I don't think that's the issue.
This happens on both the latest build, as well as the lowest one on the list, so I don't think it's because of something newly introduced.

This is a log of me opening Nethunter Terminal, typing apt-get update, which fails because it's not in chroot.  Then I type exit, bringing me to "root@kali", then type apt-get update which works as normal.
Search for "07-30 13:53:02.035 25764 25764 W" to find the first mention of nethunter terminal.
https://pastebin.com/MtqXdtzL

I'm on 6.0.1, I'm not using the stock rom since Kali has issues with it, so I'm using a Note7 port.  I'm rooted using Magisk 13.3
Nethunter zip used is "nethunter-generic-arm64-kalifs-full-rolling-3.15.4-20170629-1630", but also with the latest Nethunter terminal and Nethunter .apk from the Github.



If I manually type "Exit", I'm brought into chroot (root@kali) and I can do whatever commands I want and everything works fine.  But neither the nhterm app or the nethunter app do this automatically, which basically makes them useless.

**Comment by h313** [comment]
Could it be a problem with Magisk? Also how can we solve it?

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by h313** [comment]
Could it be a problem with Magisk? Also how can we fix it?

**Comment by FallenArchangel** [comment]
That seems to be the issue for me.
Nethunter doesn't appear to work correctly with Magisk. Uninstalling Magisk and switching to SuperSu fixed the issue.

**Comment by IDONEZEROT** [comment]
I know it's an older thread but:
Same issue on a Nexus 10 with 5.11 & SuperSU. Exit just closes the terminal.
Using terminal -> preferences -> Initial command and adding `su 0 bootkali_login`
does the trick for me.

**Comment by h313** [comment]
This issue should be closed, a Magisk module exists that fixes it now:

https://github.com/Magisk-Modules-Repo/KaliNethunter
