### ISSUE TITLE
Installing meta-packages 

### ISSUE THREAD

**Issue by webkodex** [offensive-security/kali-nethunter#922]
Device: Motorola Nexus 6 ( 32 GB)

OS version : Marshmallow

Issue: Hi i have a latest version of **nethunter (3.15)** installed & is working fine. but  In Kali Chroot Manager there is a option add meta packages, if i select & install **Kali-linux or kali-linux all** will this installation wipe out my existing nethunter or overwrite ? any advice would be helpful before i try something that will
mess up everything.
Regards
skorp

**Comment by BearChavez** [comment]
Installing them will not wipe anything, it will only install them, but make sure you have 20 GB of free space to install all of them, I would recommend only installing metapackages you need, or only install the groups of tools you need. I only installed wireless tools because that is all I need, but the choice is yours
