### ISSUE TITLE
update & Meta packages installation error from chroot  

### ISSUE THREAD

**Issue by webkodex** [offensive-security/kali-nethunter#924]
Device: **Motorola Nexus 6**

OS version **Marshmallow**

Built from repo (date and build command) or downloaded from website (links):

https://images.offensive-security.com/nethunter-release/nethunter-shamu-marshmallow-3.0.zip

 Output of `cat /proc/version` in adb shell or NetHunter Terminal:
**Linux version 3.10.40-g15269a3-dirty(root@kali) (gcc version 4.7(GCC) #3 SMP**

 Issue: am running nethunter version 3.15, I cannot install meta packages in chroot manager as i get error in kali terminal unable to locate package. **also i get error while i do apt-get update** should i update/upgrade chroot ? if yes then **how to reinstall chroot manager ?** or if its related to anything else suggest me a fix. 

Regards
skorp 
![screenshot_20170708-114918 2 1](https://user-images.githubusercontent.com/15958581/27983746-bd235f1c-63d4-11e7-8101-e21e3b91d82c.png)

![screenshot_20170708-113041 1](https://user-images.githubusercontent.com/15958581/27983641-c3955974-63d2-11e7-95e9-ea61afb961f4.png)
![screenshot_20170708-113025 1](https://user-images.githubusercontent.com/15958581/27983643-c992b39e-63d2-11e7-8603-7ce3d469f00b.png)

**Comment by binkybear** [comment]
This is due to Sana being outdated.  Will update release images in next day or two.

**Comment by webkodex** [comment]
Hi, is there any image update for sana ? how to do it ?

**Comment by True-Demon** [comment]
The smartest thing to do is to download and install the latest chroot for Kali-rolling; however, there is a slightly risky but probably okay-ish way to do it. Replace your sources.list entries with the kali-rolling entries and perform a dist-upgrade. I am testing this now, and will report back success or failure tomorrow. If you're feeling lucky, you can try what I'm about to do.

I would recommend backing up your chroot if it is important to you, but in my case, it doesn't work at all, so I copied my original sources.list file to a backup

```
cp /etc/apt/sources.list /etc/apt/sources.bak
```
After that, nano a new sources.list in the nethunter terminal like so...

```
deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
```
Uncomment deb-src line if you want source files, but there's really no reason to do this.
Ctrl+O and save, Ctrl+x to exit nano.
in the terminal run 
sudo apt-get update
wait for a few minutes...
sudo apt-get upgrade -y
wait forever...
sudo apt-get dist-upgrade -y
wait forever and a day...

If all goes well, this will upgrade the chroot to the latest Kali-rolling distro utilizing the standard ARMhf repos the same way you would if you were upgrading from Sana to Rolling on a standard desktop. I'm pretty confident all will be just fine, but better let me take the risk first since I don't really care about my phone if this somehow breaks everything. Lol :+1:

**Comment by kimocoder** [comment]
This has been told too many times allready. Be sure to check the other issue reports before filing a new one, cause the answers allready in other issue reports.

* Anyhow, thanks to @True-Demon for the correct & great answer/explain of the 'issue'

This report may be closed again.

**Comment by webkodex** [comment]
@True-Demon, @kimocoder 

Thanks for suggestion & help it WORKS !

**Comment by Nethunterlover** [comment]
Hello I have an issue in my Nexus 5 when I use wifite to hack wifi network it send some deauth packets then it's say 
Airodump-ng exited with status 1
