### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by bphd** [offensive-security/kali-nethunter#967]
### Device:

A2003

### OS version (KitKat/Lollipop/Marshmallow/Nougat):

7.1.2 secondary MultiROM

### Built from repo (date and build command) or downloaded from website (links):

https://forum.xda-developers.com/oneplus-2/development/nethunter-3-15-3-oneplus-2-cm-14-nougat-t3507548

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:

Linux version 3.10.107-Desolation (Savitar@Saturn) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jul 17 09:38:19 UTC 2017

## Issue:

+0 - Decompressing and deploying the Chroot... (~5-10min)
+0 - Error : java.lang.RuntimeException: java.lang.RuntimeException
+0 - CreateChroot >> Error: java.lang.RuntimeException: java.lang.RuntimeException

**Comment by nik012003** [comment]
I'm getting the same error on OnePlus One 8.0 Thunder Kernel(recompiled with mac8011 support).
Have you found a solution?

**Comment by pingo-power** [comment]
Nope

**Comment by nik012003** [comment]
I've installed the chroot thru the full-armhf-generic zip and it worked.

**Comment by pingo-power** [comment]
I have dropped down Kali because it's very hard to place it on a phone, specially on a MultiROMed one, but it will be a great project to be a "mobile-hacker" if the dev lay a ready-to-use rom in zip or img or more better, a ".multirom" file, you know, the third option of installation in MultiROM, a ready to install secondary rom, it will be perfect for just test it and make it more compatible for MultiROM
In state, is too hard to use it on a mobile phone (between the story of phone compatibility, Wi-Fi antens that can be switched into "modem" or "monitoring" mode so that you can see other AP and tricky configuration of this rom just for use it and lot of bugs, and non reactive dev)

**Comment by bozwald** [comment]
Just get a supported device the Nexus 5x bullhead has a fantastic nougat
and Oreo kernel and marshmallow if I remember rightly, updated as of Nov 17
with Apple pay still working, WiFi monitor mode working on tplink Alfa and
others.

Really good build

**Comment by pingo-power** [comment]
Suuuuuree, i will buy a 2013 Nexus 5x !

**Comment by bozwald** [comment]
Between that and my s8+ and my pixl I prefer the Nexus 5x everytime for a
pen test device, it has Oreo support so is still Google supported

**Comment by pingo-power** [comment]
You prefer it because it's the only phone that have a monitoring mode, right ?

**Comment by bozwald** [comment]
Yes correct, when I wanted a pen test mobile device I chose the hardware
based on my need, which was a pen testing mobile device.

The issue at hand was regarding android kernel Devs with a want to update
such a kernel to have such features.

Also it was handy that Nexus have unlocked bootloaders out of the box

**Comment by pingo-power** [comment]
Does exist a list of hardware that can be used for pentest ? On mobile phone

**Comment by bozwald** [comment]
I think the wiki is out of date unfortunately but the tickets here are a
good source of what works and doesn't.

**Comment by pingo-power** [comment]
It say my phone is supported, so why ?

**Comment by bozwald** [comment]
It likely once was or is now the one plus one has been superseded since and
this is a community driven project the Devs must have a need to update it
to put their time into it we wish their were more Devs but they're hiding
away/busy

On 20 Feb 2018 5:28 pm, "pingo-power" <notifications@github.com> wrote:

It say my phone is supported, so why ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/offensive-security/kali-nethunter/issues/967#issuecomment-367053788>,
or mute the thread

**Comment by Rumpelstilzli** [comment]
> 
> ### Device:
> 
> A2003
> ### OS version (KitKat/Lollipop/Marshmallow/Nougat):
> 
> 7.1.2 secondary MultiROM
> ### Built from repo (date and build command) or downloaded from website (links):
> 
> https://forum.xda-developers.com/oneplus-2/development/nethunter-3-15-3-oneplus-2-cm-14-nougat-t3507548
> ### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
> 
> Linux version 3.10.107-Desolation (Savitar@Saturn) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Mon Jul 17 09:38:19 UTC 2017
> ## Issue:
> 
> +0 - Decompressing and deploying the Chroot... (~5-10min)
> +0 - Error : java.lang.RuntimeException: java.lang.RuntimeException
> +0 - CreateChroot >> Error: java.lang.RuntimeException: java.lang.RuntimeException

I had the same issue with my Pixel 2
To fix the issue you have to download/update busybox
